{{- if  .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "redis-operator.labels" . | nindent 4 }}
  name: {{ include "redis-operator.fullname" . }}
spec:
  endpoints:
    - interval: 30s
      port: redis-operator
  selector:
    matchLabels:
      {{- include "redis-operator.selectorLabels" . | nindent 6 }}
{{- end }}
