apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-operator.fullname" . }}
  labels:
    {{- include "redis-operator.labels" . | nindent 4 }}
spec:
  selector:
      {{- include "redis-operator.selectorLabels" . | nindent 4 }}
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: redis-operator
  - name: operate
    port: 8089
    protocol: TCP
    targetPort: 8089
  type: ClusterIP
