baselineName:
  - name: "Cluster Mode"
    name-zh: "集群模式"
  - name: "Cluster Proxy Mode"
    name-zh: "集群代理模式"
  - name: "Sentinel Mode"
    name-zh: "哨兵模式"
  - name: "Sentinel Mode A-A"
    name-zh: "哨兵模式-双活"
  - name: "Sentinel Proxy Mode"
    name-zh: "哨兵代理模式"
  - name: "Sentinel Proxy Mode A-A"
    name-zh: "哨兵代理模式-双活"
  - name: "RedisOperator Standard"
    name-zh: "RedisOperator标准版"
  - name: "RedisOperator HighAvailability"
    name-zh: "RedisOperator高可用版"
description:
  - name: "Redis Caching Database"
    name-zh: "Redis 缓存数据库"

  - name: "Cluster Mode Baseline, incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "集群模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
  - name: "High Availability/HA Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "高可用版基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."

  - name: "Standard Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "标准版基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
  - name: "Cluster Proxy Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "集群代理模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."

  - name: "Sentinel Proxy mode,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "哨兵代理模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
  - name: "Sentinel mode,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
    name-zh: "哨兵模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."


  - name: "Please enter a custom quota, the unit is `Core`"
    name-zh: "请输入自定义配额,单位为Core"
  - name: "Please enter a custom quota, the unit is `Gi`"
    name-zh: "请输入自定义配额,单位为Gi"
  - name: "Minimum number of shards is 3"
    name-zh: "分片数，最小为三分片"
  - name: "The number of instances you entered is invalid. The minimum number of instances is 1. Please adjust and resubmit"
    name-zh: "当前输入的实例数不符合规范，实例数最低为1，请调整后再次提交"
  - name: "Number of shards, minimum is 1"
    name-zh: "分片数，最小为单分片"
  - name: "Please enter the storage size"
    name-zh: "请输入存储大小"
  - name: "Please select storage"
    name-zh: "请选择存储"
  - name: "Please enter a password consisting of English letters, numbers, or the special characters \"/ ~ % _ . ^ + = - [ ] :\", with a length between 1 and 32 characters."
    name-zh: "请输入由英文字母、数字或特殊字符“/ ~ % _ . ^ + = - [ ] :”组成且长度在1-32个字符范围内的密码信息"
  - name: "Please enter a valid port number"
    name-zh: "请输入合法端口号"
  - name: "Minimum storage size is 1"
    name-zh: "存储大小最低为1"
  - name: "Please enter a password consisting of English letters, numbers, or the special characters \"/ ~ % _ . ^ + = - [ ] : \""
    name-zh: "由英文字母、数字或特殊字符“/ ~ % _ . ^ + = - [ ] : ”组成的密码信息"
  - name: "Password length must be between 1 and 32 characters"
    name-zh: "长度需要1-32之间"

placeholder:
  - name: "Please enter a custom quota, the unit is `Gi`"
    name-zh: "请输入自定义配额,单位为Gi"
  - name: "Please enter a custom quota, the unit is `Core`"
    name-zh: "请输入自定义配额,单位为Core"
  - name: "Please enter the storage size"
    name-zh: "请输入存储大小"
  - name: "Please select storage"
    name-zh: "请选择存储"
  - name: "Please enter the number of instances"
    name-zh: "请输入实例数"
  - name: "Enter your admin password"
    name-zh: "输入管理员账户密码"
  - name: "Please enter the port number and press Enter to add it."
    name-zh: "请输入端口号，点击回车进行添加"

label:
  - name: "Administrator password"
    name-zh: "管理员账号密码"
  - name: "Memory"
    name-zh: "内存"
  - name: "Replicas"
    name-zh: "实例数"
  - name: "Version"
    name-zh: "版本"

  - name: "StorageSize"
    name-zh: "存储大小"

  - name: "StorageClass"
    name-zh: "存储类"
  - name: "Load Balancer Controller"
    name-zh: "负载均衡控制器名称"
  - name: "Load Balancer Address"
    name-zh: "负载均衡地址"
  - name: "Redis Node Port"
    name-zh: "Redis节点端口"
  - name: "Sentinel Port"
    name-zh: "哨兵端口"
  - name: "Redis Bus Port"
    name-zh: "Redis总线端口"
  - name: "protocol"
    name-zh: "协议"
  - name: "Deployment Method"
    name-zh: "部署方式"
  - name: "Deployment"
    name-zh: "无状态部署"
  - name: "StatefulSet"
    name-zh: "有状态部署"
  - name: "Sentinel Authentication"
    name-zh: "哨兵认证"

actionAliasName:
  - name: "MasterSlaveSwitchover"
    name-zh: "主从切换"
  - name: "Automatic switch"
    name-zh: "自动切换"
  - name: "Middleware Restart"
    name-zh: "服务重启"
  - name: "Services Exposure-External Access"
    name-zh: "服务暴露-集群外访问"
  - name: "Services Exposure-R/W split"
    name-zh: "服务暴露-读写分离"
  - name: "Services Exposure-Sentinel"
    name-zh: "服务暴露-哨兵"
  - name: "Services Exposure-Read-Only"
    name-zh: "服务暴露-只读"
  - name: "Services Exposure-Read-Write"
    name-zh: "服务暴露-读写"


