mainVersionGroups:
  "7.2":
    - "7.2.14"
    - "7.2.4"
  "8.2":
    - "8.2.6"
crossUpgradeRules:
  "7.2":
    - "7.2"
    - "8.2"
  "8.2":
    - "8.2"
crossDowngradeRules:
  "7.2":
    - "7.2"
  "8.2":
    - "8.2"
