mainVersionGroups:
  "6.x":
    - "6.2.19"
  "7.2":
    - "7.2.10"
    - "7.2.4"
  "7.0":
    - "7.0.12"
    - "7.0.15"
  "7.4":
    - "7.4.5"
  "8.0":
    - "8.0.4"
  "8.2":
    - "8.2.2"

crossUpgradeRules:
  "6.x":
    - "6.x"
    - "7.0"
    - "7.2"
    - "7.4"
    - "8.0"
    - "8.2"
  "7.2":
    - "7.2"
    - "7.4"
    - "8.0"
    - "8.2"
  "7.4":
    - "7.4"
    - "8.0"
    - "8.2"
  "7.0":
    - "7.0"
    - "7.2"
    - "7.4"
    - "8.0"
    - "8.2"
  "8.0":
    - "8.0"
    - "8.2"
  "8.2":
    - "8.2"
crossDowngradeRules:
  "6.x":
    - "6.x"
  "7.0":
    - "7.0"
  "7.2":
    - "7.2"
  "7.4":
    - "7.4"
  "8.0":
    - "8.0"
  "8.2":
    - "8.2"
