apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: pre-redis-tolerations
spec:
  baselineType: "PreAction"
  actionType: "tolerations"
  necessary:
    tolerations: "array"
  steps:
    - name: tolerations
      type: "KubectlEdit" # KubectlGet、KubectlEdit、KubectlExec、Exec、HTTP
      cue: |
        output: {
          spec: parameters.spec
        }
        parameters: {
          spec: {
            parameters: {
              {{- if .Necessary.tolerations }}
              statefulset: {
                spec: {
                  template: {
                    spec: {
                      {{- with .Necessary.tolerations }}
                      tolerations: {{ toCue . }}
                      {{- end }}
                    }
                  }
                }
              }
              {{- end }}
              {{- if eq .Parameters.type "sentinel" }}
              deployment: {
                spec: {
                  template: {
                    spec: {
                      {{- with .Necessary.tolerations }}
                      tolerations: {{ toCue . }}
                      {{- end }}
                    }
                  }
                }
              }
              {{- end }}
              {{- if .Necessary.tolerations }}
              {{- with .Necessary.tolerations }}
              pod: [
                {
                  tolerations: {{ toCue . }}
                },
              ]
              {{- end }}
              {{- end }}
              {{- if .Parameters.predixy }}
              predixy: {
                {{- with .Necessary.tolerations }}
                tolerations: {{ toCue . }}
                {{- end }}
              }
              {{- end }}
            }
          }
          resource: {
            apiversion: "middleware.cn/v1"
            kind: "Middleware"
            name: "{{ .Globe.Name }}"
            namespace: "{{ .Globe.Namespace }}"
          }
        }
