apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: redis-alertrule
spec:
  template: |
    apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: {{ .Globe.Name }}
      labels:
        prometheus: k8s
        role: alert-rules
    spec:
      groups:
        {{- if eq .Values.predixy.enableProxy "true" }}
        - name: redis-proxy
          rules:
          - alert: MismatchedRequestResponseRate
            expr: abs(rate(predixy_cluster_total_requests{cluster='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"}[5m]) - rate(predixy_cluster_total_respones{cluster='{{ .Globe.Name }}'}[5m])) > 50
            for: 5m
            labels:
              severity: warning
              project: zeus
              subject: middleware
              {{- with .Values.labels }}
              {{ toYaml . }}
              {{- end }}
            annotations:
              message: "Mismatched request/response rate detected on redis proxy. (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }})"
              metric: predixy_cluster_total_requests
              product: harmonycloud
              service: metrics
        {{- end }}
        - name: redis-exporter
          rules:
          - alert: ReidsExporterDown
            annotations:
              message: "Redis Exporter is down. (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }}, Pod: {{`{{ $labels.pod }}`}})"
              metric: up
              product: harmonycloud
              service: metrics
            expr: up{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"} == 0
            for: 5m
            labels:
              severity: warning
              project: zeus
              subject: middleware
              {{- with .Values.labels }}
              {{ toYaml . }}
              {{- end }}
        - name: redis-rules
          rules:
            - alert: RedisFailOver
              expr: rate(slave_failover_total{name="{{ .Globe.Name }}",target_namespace={{ .Globe.Namespace | quote }}}[3m]) > 0
              for: 30s
              labels:
                severity: warning
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
              annotations:
                product: harmonycloud
                service: metrics
                message: "Redis instance failover. (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }})"
            - alert: RedisUnhealthy
              expr: redis_up{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"} < 1 or kube_pod_container_status_running{container="redis-cluster", pod=~'{{ .Globe.Name }}-[0-9]|{{ .Globe.Name }}-shard-[0-9]-[0-9]'} == 0
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
              annotations:
                product: harmonycloud
                service: metrics
                message: "Redis instance is unhealthy. (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }})"
            - alert: RedisLargConnect
              expr: redis_connected_clients{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"} * 100/redis_config_maxclients{service='{{ .Globe.Name }}', namespace="{{ .Globe.Namespace }}"} > 80
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
              annotations:
                product: harmonycloud
                service: metrics
                message: 'Redis client connections account for {{ `{{ printf "%.0f" $value }}` }}% of the redis_config_maxclients configuration. (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }})'
            - alert: RedisLargeBlockConnect
              expr: redis_blocked_clients{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"} * 100/redis_connected_clients{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"} > 20
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
              annotations:
                product: harmonycloud
                service: metrics
                message: 'Redis block connections account for {{ `{{ printf "%.0f" $value }}` }}% of the redis client connections.. (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }})'
            - alert: RedisReplicationBroken
              expr: delta(redis_connected_slaves{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"}[3m]) < 0
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
              annotations:
                message: "Redis instance lost a slave. (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }}, Pod: {{`{{ $labels.pod }}`}})"
            - alert: RedisOutOfConfiguredMaxmemory
              expr:  (redis_memory_used_bytes{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"} * 100 / redis_memory_max_bytes{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"}) > 90 and redis_memory_max_bytes{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"}!=0
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
              annotations:
                message: 'Redis is running out of configured maxmemory (> current_value={{ `{{ printf "%.0f" $value }}` }}%). (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }}, Pod: {{`{{ $labels.pod }}`}})'
            - alert: RedisVolumeUsage70
              expr:  (100 * kube_persistentvolumeclaim_info{namespace='{{ .Globe.Namespace }}', persistentvolumeclaim=~"redis-data-{{ .Globe.Name }}.*"}) * on(volumename) group_left max(label_replace ((used_size_kb / total_size_kb),"volumename", "$1", "pv", "(.+)")) by (volumename) > 70
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
              annotations:
                product: harmonycloud
                message: 'The disk usage of Redis has exceeded 70%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }}, Persistentvolumeclaim: {{`{{ $labels.persistentvolumeclaim }}`}})'
            - alert: RedisVolumeUsage85
              expr:  (100 * kube_persistentvolumeclaim_info{namespace='{{ .Globe.Namespace }}', persistentvolumeclaim=~"redis-data-{{ .Globe.Name }}.*"}) * on(volumename) group_left max(label_replace ((used_size_kb / total_size_kb),"volumename", "$1", "pv", "(.+)")) by (volumename) > 85
              for: 5m
              labels:
                severity: critical
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
              annotations:
                product: harmonycloud
                message: 'The disk usage of Redis has exceeded 85%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }}, Persistentvolumeclaim: {{`{{ $labels.persistentvolumeclaim }}`}})'
            - alert: RedsMemoryUsageHigh
              annotations:
                message: 'The memory usage of Redis has exceeded 90%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }}, Pod: {{`{{ $labels.pod }}`}})'
              expr: 100 * sum(container_memory_working_set_bytes{namespace='{{ .Globe.Namespace }}',pod=~'{{ .Globe.Name }}-[0-9]|{{ .Globe.Name }}-shard-[0-9]-[0-9]',endpoint!="",container!=""}) by (pod) / sum(kube_pod_container_resource_requests{namespace='{{ .Globe.Namespace }}',pod=~'{{ .Globe.Name }}-[0-9]|{{ .Globe.Name }}-shard-[0-9]-[0-9]',resource="memory"}) by (pod) > 90
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
            - alert: RedisCpuUsageHigh
              annotations:
                message: 'The cpu usage of Redis has exceeded 90%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }}, Pod: {{`{{ $labels.pod }}`}})'
              expr: 100 * sum(rate (container_cpu_usage_seconds_total{namespace='{{ .Globe.Namespace }}',pod=~'{{ .Globe.Name }}-[0-9]|{{ .Globe.Name }}-shard-[0-9]-[0-9]',endpoint!="",container!=""}[5m]) ) by (pod) / sum(kube_pod_container_resource_requests{namespace='{{ .Globe.Namespace }}',pod=~'{{ .Globe.Name }}-[0-9]|{{ .Globe.Name }}-shard-[0-9]-[0-9]',resource="cpu"}) by (pod)  > 90
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
        {{- if eq .Values.type "sentinel" }}
        - name: redis-sentinel
          rules:
            - alert: RedisSentinelWatchNodeUnhealthy
              expr: redis_sentinel_master_status{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"} == 0
              for: 5m
              labels:
                severity: critical
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
              annotations:
                product: harmonycloud
                service: metrics
                message: "Redis master node monitored by the sentinel is unhealthy. (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }})"
            - alert: RedisSentries_num
              expr: redis_sentinel_master_sentinels{service='{{ .Globe.Name }}',namespace="{{ .Globe.Namespace }}"}%2 == 0
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: middleware
                {{- with .Values.labels }}
                {{ toYaml . }}
                {{- end }}
              annotations:
                product: harmonycloud
                service: metrics
                message: "Redis sentinel num is not right,  current_value={{ `{{ $value }}` }}. (Namespace: {{ .Globe.Namespace }}, ServiceName: {{ .Globe.Name }})"
        {{- end }}