# Copyright 2025 OpenSaola Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: redis-operator-alertrule
spec:
  template: |
    {{- if  .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
    apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      labels:
        prometheus: k8s
        platform: zeus
        role: alert-rules
      annotations:
        target_alias_name: 平台系统监控
        target_name: platform
        target_type: system
      name: {{ .Globe.Name }}-rules
    spec:
      groups:
        - name: middleware-rules
          rules:
            - alert: redisOperatorCpuUsageHigh
              annotations:
                message: 'The cpu usage of Redis Operator has exceeded 90%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Globe.Namespace }}, Pod: {{`{{ $labels.pod }}`}})'
              expr: (sum by (pod) (rate(container_cpu_usage_seconds_total{image!="",container!~"|POD",endpoint!="", pod=~"redis-operator.+",namespace="middleware-operator"}[5m])))  * 100 / (sum by (pod) (kube_pod_container_resource_requests{resource="cpu", container=~"redis-operator", pod=~"redis-operator.+", namespace="middleware-operator"})) > 90
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: operator
                {{- with .Values.labels }}
                {{- toYaml . | nindent 12 }}
                {{- end }}
            - alert: redisOperatorMemoryUsageHigh
              annotations:
                message: 'The memory usage of Redis Operator has exceeded 90%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Globe.Namespace }}, Pod: {{`{{ $labels.pod }}`}})'
              expr: (sum by (pod)(container_memory_working_set_bytes{container!~"|POD",endpoint!="",pod=~"redis-operator.+",namespace="middleware-operator"})) * 100 / (sum by (pod) (kube_pod_container_resource_requests{container=~"redis-operator",resource="memory",pod=~"redis-operator.+",namespace="middleware-operator"})) > 90
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: operator
                {{- with .Values.labels }}
                {{- toYaml . | nindent 12 }}
                {{- end }}
            - alert: redisOperatorInstanceNotRunning
              annotations:
                message: "Redis operator instances stopped working.(Namespace: {{ .Globe.Namespace }}, Pod: {{`{{ $labels.pod }}`}})"
              expr: |-
                kube_pod_container_status_running{container="redis-operator",namespace="middleware-operator"} == 0
              for: 5m
              labels:
                severity: warning
                project: zeus
                subject: operator
                {{- with .Values.labels }}
                {{- toYaml . | nindent 12 }}
                {{- end }}
            - alert: multipleRedisOperatorInstanceNotRunning
              annotations:
                message: "Multiple Redis operator instances stopped running.(Namespace: {{ .Globe.Namespace }}, Pod: {{`{{ $labels.pod }}`}})"
              expr: count(kube_pod_container_status_running{container="redis-operator",namespace="middleware-operator"} == 0) > 1
              for: 5m
              labels:
                severity: critical
                project: zeus
                subject: operator
                {{- with .Values.labels }}
                {{- toYaml . | nindent 12 }}
                {{- end }}
    {{- end }}