# Copyright 2025 OpenSaola Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: redis-predixy-servicemonitor
spec:
  template: |
    {{- if  .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
    {{- if eq .Values.predixy.enableProxy "true" }}
    apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      labels:
        app: {{ .Globe.Name }}
      name: {{ .Globe.Name }}-proxy
    spec:
      endpoints:
        - interval: 30s
          port: proxy-exporter
          relabelings:
          - replacement: redis
            targetLabel: middleware
          - sourceLabels: [service]
            replacement: {{ .Globe.Name }}
            targetLabel: service
      selector:
        matchLabels:
          app: {{ .Globe.Name }}
          component: {{ .Globe.Name }}-predixy
    {{- end }}
    {{- end }}