apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: redis-config
spec:
  template: |
    {{- define "helm.function.ifListMapHasValue" -}}
      {{- $list := index . 0 -}}
      {{- $Key := index . 1 -}}
      {{- $targetValue := index . 2 -}}
      {{- $defaultValue := index . 3 -}}
    
      {{- $value := $defaultValue -}}
    
      {{- range $list -}}
        {{- if eq (index . $Key) $targetValue -}}
          {{- $value = $targetValue -}}
        {{- end -}}
      {{- end -}}
      {{- $value -}}
    {{- end -}}
    
    {{- define "redis.maxMemory" -}}
    {{- if .Values.args.maxmemory }}
        {{- .Values.args.maxmemory }}
    {{- else }}
        {{- include "redis.cal.memory" (list .Values.redis.resources.limits.memory "max") }}
    {{- end }}
    {{- end -}}

    {{- define "redis.cal.memory" -}}
        {{- $memoryRaw := index . 0 }}
        {{- $target := index . 1 }}
    
        {{- $maxmemory := 0}}
        {{- $hardLimit := 0}}
        {{- $softLimit := 0}}
    
        {{- $memory := regexFind "[0-9]*[.]*[0-9]*" $memoryRaw }}
        {{- $memoryB := 0 }}
    
        {{- if contains "." $memory }}
            {{- $memoryLs := regexSplit "\\." ($memory | toString) -1 }}
            {{- $memoryInt := index $memoryLs 0 }}
            {{- $memoryDecimal := index $memoryLs 1 }}
            {{- $memoryDecimalLen := len $memoryDecimal }}
            {{- $memoryDecimalDigit := 1 }}
            {{- range untilStep 0 $memoryDecimalLen 1 }}
                {{- $memoryDecimalDigit = mul $memoryDecimalDigit 10 }}
            {{- end }}
            {{- if contains "GI" (upper $memoryRaw) }}
                {{- $memoryB = add (mul ($memoryInt | int) 1024 1024 1024) (div (mul ($memoryDecimal | int) 1024 1024 1024) $memoryDecimalDigit) }}
            {{- else if contains "G" (upper $memoryRaw) }}
                {{- $memoryB = add (mul ($memoryInt | int) 1000 1000 1000) (div (mul ($memoryDecimal | int) 1000 1000 1000) $memoryDecimalDigit) }}
            {{- else if contains "MI" (upper $memoryRaw) }}
                {{- $memoryB = add (mul ($memoryInt | int) 1024 1024) (div (mul ($memoryDecimal | int) 1024 1024) $memoryDecimalDigit) }}
            {{- else if contains "M" (upper $memoryRaw) }}
                {{- $memoryB = add (mul ($memoryInt | int) 1000 1000) (div (mul ($memoryDecimal | int) 1000 1000) $memoryDecimalDigit) }}
            {{- end }}
        {{- else }}
            {{- if contains "GI" (upper $memoryRaw) }}
                {{- $memoryB = mul $memory 1024 1024 1024 }}
            {{- else if contains "G" (upper $memoryRaw) }}
                {{- $memoryB = mul $memory 1000 1000 1000 }}
            {{- else if contains "MI" (upper $memoryRaw) }}
                {{- $memoryB = mul $memory 1024 1024 }}
            {{- else if contains "M" (upper $memoryRaw) }}
                {{- $memoryB = mul $memory 1000 1000 }}
            {{- end }}
        {{- end }}
    
        {{- $memory = div (div $memoryB 1024) 1024 }}
        {{- $maxmemory = div (mul $memory 4) 5 }}
        {{- $hardLimit = div (mul $memory 4) 5 }}
        {{- $softLimit = div (mul $memory 2) 5 }}
    
        {{- if eq $target "max" }}
            {{- printf "%dmb" $maxmemory }}
        {{- else if eq $target "hard" }}
            {{- printf "%dmb" $hardLimit }}
        {{- else if eq $target "soft" }}
            {{- printf "%dmb" $softLimit }}
        {{- end }}
    {{- end -}}

    {{- define "redis.outputbuff.slave.hard" -}}
    {{- if .Values.args.maxmemory }}
        {{- include "redis.cal.memory" (list .Values.args.maxmemory "hard") }}
    {{- else }}
        {{- include "redis.cal.memory" (list .Values.redis.resources.limits.memory "hard") }}
    {{- end }}
    {{- end -}}
    
    {{- define "redis.outputbuff.slave.soft" -}}
    {{- if .Values.args.maxmemory }}
        {{- include "redis.cal.memory" (list .Values.args.maxmemory "soft") }}
    {{- else }}
        {{- include "redis.cal.memory" (list .Values.redis.resources.limits.memory "soft") }}
    {{- end }}
    {{- end -}}
    
    {{- define "redis.cal.memory" -}}
        {{- $memoryRaw := index . 0 }}
        {{- $target := index . 1 }}
    
        {{- $maxmemory := 0}}
        {{- $hardLimit := 0}}
        {{- $softLimit := 0}}
    
        {{- $memory := regexFind "[0-9]*[.]*[0-9]*" $memoryRaw }}
        {{- $memoryB := 0 }}
    
        {{- if contains "." $memory }}
            {{- $memoryLs := regexSplit "\\." ($memory | toString) -1 }}
            {{- $memoryInt := index $memoryLs 0 }}
            {{- $memoryDecimal := index $memoryLs 1 }}
            {{- $memoryDecimalLen := len $memoryDecimal }}
            {{- $memoryDecimalDigit := 1 }}
            {{- range untilStep 0 $memoryDecimalLen 1 }}
                {{- $memoryDecimalDigit = mul $memoryDecimalDigit 10 }}
            {{- end }}
            {{- if contains "GI" (upper $memoryRaw) }}
                {{- $memoryB = add (mul ($memoryInt | int) 1024 1024 1024) (div (mul ($memoryDecimal | int) 1024 1024 1024) $memoryDecimalDigit) }}
            {{- else if contains "G" (upper $memoryRaw) }}
                {{- $memoryB = add (mul ($memoryInt | int) 1000 1000 1000) (div (mul ($memoryDecimal | int) 1000 1000 1000) $memoryDecimalDigit) }}
            {{- else if contains "MI" (upper $memoryRaw) }}
                {{- $memoryB = add (mul ($memoryInt | int) 1024 1024) (div (mul ($memoryDecimal | int) 1024 1024) $memoryDecimalDigit) }}
            {{- else if contains "M" (upper $memoryRaw) }}
                {{- $memoryB = add (mul ($memoryInt | int) 1000 1000) (div (mul ($memoryDecimal | int) 1000 1000) $memoryDecimalDigit) }}
            {{- end }}
        {{- else }}
            {{- if contains "GI" (upper $memoryRaw) }}
                {{- $memoryB = mul $memory 1024 1024 1024 }}
            {{- else if contains "G" (upper $memoryRaw) }}
                {{- $memoryB = mul $memory 1000 1000 1000 }}
            {{- else if contains "MI" (upper $memoryRaw) }}
                {{- $memoryB = mul $memory 1024 1024 }}
            {{- else if contains "M" (upper $memoryRaw) }}
                {{- $memoryB = mul $memory 1000 1000 }}
            {{- end }}
        {{- end }}
    
        {{- $memory = div (div $memoryB 1024) 1024 }}
        {{- $maxmemory = div (mul $memory 4) 5 }}
        {{- $hardLimit = div (mul $memory 4) 5 }}
        {{- $softLimit = div (mul $memory 2) 5 }}
    
        {{- if eq $target "max" }}
            {{- printf "%dmb" $maxmemory }}
        {{- else if eq $target "hard" }}
            {{- printf "%dmb" $hardLimit }}
        {{- else if eq $target "soft" }}
            {{- printf "%dmb" $softLimit }}
        {{- end }}
    {{- end -}}

    {{$customVolumeLogName := "redis-logs"}}
    {{$customVolumeDataName := "redis-data"}}
    
    {{- if .Values.customVolumes }}
    {{$customVolumeLogName = include "helm.function.ifListMapHasValue" (list .Values.customVolumes "name" "redis-logs" "redis-data") }}
    {{- end }}
    
    {{$maxMemory := include "redis.maxMemory" . }}
    {{$replciaHardLimit := include "redis.outputbuff.slave.hard" . }}
    {{$replciaSoftLimit := include "redis.outputbuff.slave.soft" . }}

    apiVersion: v1
    data:
      redis.conf: |-
      {{- if eq .Values.type "sentinel" }}
        slaveof 127.0.0.1 6379
        cluster-enabled no
      {{- else if eq .Values.type "cluster" }}
        cluster-enabled yes
      {{- else if eq .Values.type "clusterMultiSts" }}
        cluster-enabled yes
      {{- end }}
        masterauth {REDIS_PASS}
        appendonly {{ .Values.args.appendonly | default "no" }}
        lua-time-limit {{ index .Values.args "lua-time-limit" | default 5000 }}
        slowlog-log-slower-than {{ index .Values.args "slowlog-log-slower-than" | default 10000 }}
        maxmemory {{ $maxMemory }}
        zset-max-ziplist-entries {{ index .Values.args "zset-max-ziplist-entries" | default 128 }}
        cluster-config-file nodes-{REDIS_INSTANCE_PORT}.conf
        save {{ .Values.args.save | default "60 10000" }}
        tcp-backlog {{ index .Values.args "tcp-backlog" | default 511 }}
        tcp-keepalive {{ index .Values.args "tcp-keepalive" | default 60 }}
        {{- if .Values.customVolumes }}
        {{- range $key, $value := .Values.customVolumes }}
        {{- if eq $value.name $customVolumeDataName }}
        dir {{ $value.mountPath }}
        {{- end }}
        {{- end }}
        {{- else }}
        dir /{PATH_PREFIX}/redis/{DOMAIN_NAME}/{NAMESPACE}/{REDIS_CLUSTER_NAME}/{POD_NAME}/data
        {{- end }}
        stop-writes-on-bgsave-error {{ index .Values.args "stop-writes-on-bgsave-error" | default "no" }}
        slave-serve-stale-data {{ index .Values.args "slave-serve-stale-data" | default "yes" }}
        timeout {{ .Values.args.timeout | default 300 }}
        pidfile /{PATH_PREFIX}/redis/{DOMAIN_NAME}/{NAMESPACE}/{REDIS_CLUSTER_NAME}/{POD_NAME}/log/redis-{REDIS_INSTANCE_PORT}.pid
        activerehashing {{ .Values.args.activerehashing | default "yes" }}
        cluster-announce-ip {PODIP}
        dbfilename dump-{REDIS_INSTANCE_PORT}.rdb
        hz {{ .Values.args.hz | default 10 }}
        bind {PODIP} 127.0.0.1
        cluster-node-timeout {{ index .Values.args "cluster-node-timeout" | default 15000 }}
        repl-timeout {{ index .Values.args "repl-timeout" | default "60" }}
        repl-backlog-size {{ index .Values.args "repl-backlog-size" | default "256mb" }}
        repl-diskless-sync {{ index .Values.args "repl-diskless-sync" | default "no" }}
        repl-diskless-sync-delay {{ index .Values.args "repl-diskless-sync-delay" | default 5 }}
        hash-max-ziplist-value {{ index .Values.args "hash-max-ziplist-value" | default 64 }}
        databases {{ .Values.args.databases | default 16 }}
        slave-read-only {{ index .Values.args "slave-read-only" | default "yes" }}
        daemonize {{ .Values.args.daemonize | default "no" }}
        latency-monitor-threshold {{ index .Values.args "latency-monitor-threshold" | default 0 }}
        hash-max-ziplist-entries {{ index .Values.args "hash-max-ziplist-entries" | default 512 }}
        {{- if .Values.customVolumes }}
        {{- range $key, $value := .Values.customVolumes }}
        {{- if eq $value.name $customVolumeLogName }}
        logfile {{ $value.mountPath }}/{SYS_CODE}-{REDIS_INSTANCE_PORT}.log
        {{- end }}
        {{- end }}
        {{- else }}
        logfile "{PATH_PREFIX}/redis/{DOMAIN_NAME}/{NAMESPACE}/{REDIS_CLUSTER_NAME}/{POD_NAME}/log/{SYS_CODE}-redis-{REDIS_INSTANCE_PORT}.log"
        {{- end }}
        {{- if semverCompare ">=6.0.0" .Values.version }}
        aclfile "{PATH_PREFIX}/redis/{DOMAIN_NAME}/{NAMESPACE}/{REDIS_CLUSTER_NAME}/{POD_NAME}/config/user.acl"
        {{- end }}
        rdbchecksum {{ .Values.args.rdbchecksum | default "yes" }}
        cluster-require-full-coverage {{ index .Values.args "cluster-require-full-coverage" | default "no" }}
        client-output-buffer-limit {{ index .Values.args "client-output-buffer-limit" | default (printf "replica %s %s 120" $replciaHardLimit $replciaSoftLimit) }}
        maxclients {{ .Values.args.maxclients | default 15000 }}
        slave-priority {{ index .Values.args "slave-priority" | default 100 }}
        hll-sparse-max-bytes {{ index .Values.args "hll-sparse-max-bytes" | default 3000 }}
        repl-disable-tcp-nodelay {{ index .Values.args "repl-disable-tcp-nodelay" | default "no" }}
        port {REDIS_INSTANCE_PORT}
        slowlog-max-len {{ index .Values.args "slowlog-max-len" | default 1000 }}
        loglevel {{ .Values.args.loglevel | default "notice" }}
        set-max-intset-entries {{ index .Values.args "set-max-intset-entries" | default 512 }}
        zset-max-ziplist-value {{ index .Values.args "zset-max-ziplist-value" | default 64 }}
        rdbcompression {{ .Values.args.rdbcompression | default "yes" }}
        requirepass {REDIS_PASS}
        maxmemory-policy {{ index .Values.args "maxmemory-policy" | default "volatile-lru" }}
        lfu-decay-time {{ index .Values.args "lfu-decay-time" | default 1 }}
        cluster-replica-validity-factor {{ index .Values.args "cluster-replica-validity-factor" | default 0 }}
        lazyfree-lazy-expire {{ index .Values.args "lazyfree-lazy-expire" | default "yes" }}
        lazyfree-lazy-server-del {{ index .Values.args "lazyfree-lazy-server-del" | default "yes" }}
        {{- if semverCompare ">=6.2.6" .Values.version }}
        ignore-warnings ARM64-COW-BUG
        {{- end }}
        {{- if .Values.args.renameCommand }}
        {{- range $command := .Values.args.renameCommand }}
        rename-command {{$command}}
        {{- end }}
        {{- end }}
        {{- range $k, $v := .Values.additionArgs }}
        {{$k}} {{$v}}
        {{- end }}
    kind: ConfigMap
    metadata:
      name: {{ .Globe.Name }}-config