# Copyright 2025 OpenSaola Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: redis-sentinel-configmap
spec:
  template: |
    {{ if eq .Values.type "sentinel" }}
    {{- $password := .Values.redisPassword -}}
    {{- if .Values.encodePassword -}}
    {{- $password = (b64dec .Values.encodePassword) | default .Values.redisPassword -}}
    {{- end -}}
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ .Globe.Name }}-sentinel
      namespace: {{ .Globe.Namespace }}
      labels:
        app.kubernetes.io/name: {{ .Globe.Name }}
        app.kubernetes.io/instance: {{ .Globe.Name }}
        app.kubernetes.io/component: sentinel
    data:
      sentinel.conf: |
        port {{ .Values.sentinel.port }}
        sentinel monitor mymaster 127.0.0.1 {{ .Values.redis.port }} {{ div .Values.sentinel.replicas 2 | add 1 }}
        sentinel down-after-milliseconds mymaster {{ .Values.sentinel.args.downAfterMilliseconds | default 1000 }}
        sentinel failover-timeout mymaster {{ .Values.sentinel.args.failoverTimeout | default 3000 }}
        sentinel parallel-syncs mymaster {{ .Values.sentinel.args.parallelSyncs | default 2 }}
        sentinel auth-pass mymaster {{ $password }}
        {{- if .Values.sentinel.auth }}
        requirepass {{ $password }}
        {{- end }}
    {{ end }}
