apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: redis-sentinel-configmap
spec:
  template: |
    {{ if eq .Values.type "sentinel" }}
    {{- $password := .Values.redisPassword -}}
    {{- if .Values.encodePassword -}}
    {{- $password = (b64dec .Values.encodePassword) | default .Values.redisPassword -}}
    {{- end -}}
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ .Globe.Name }}-sentinel-config
      namespace: {{ .Globe.Namespace }}
      labels:
        app.kubernetes.io/name: {{ .Globe.Name }}
        app.kubernetes.io/instance: {{ .Globe.Name }}
        app.kubernetes.io/component: sentinel
    data:
      sentinel.conf: |
        port {{ .Values.sentinel.port }}
        sentinel monitor mymaster 127.0.0.1 {{ .Values.redis.port }} {{ div .Values.sentinel.replicas 2 | add 1 }}
        sentinel down-after-milliseconds mymaster {{ .Values.sentinel.downAfterMilliseconds | default 5000 }}
        sentinel failover-timeout mymaster {{ .Values.sentinel.failoverTimeout | default 180000 }}
        sentinel parallel-syncs mymaster {{ .Values.sentinel.parallelSyncs | default 1 }}
        sentinel auth-pass mymaster {{ $password }}
        requirepass {{ $password }}
    {{ end }}
