annotations:
  deprecatedVersion: 5.0.8,6.2.6,6.2.11
  owner: harmonycloud
  type: db
  version: 6.2.18,6.2.16,7.2.8,7.2.4,7.0.12,7.0.15
apiVersion: v2
appVersion: 7.2.8
dependencies:
- alias: redis-operator
  condition: redis-operator.enabled
  name: redis-operator
  repository: file://./charts/redis-operator
  version: 2.15.0
description: CloudDB Redis缓存数据库
name: redis
type: application
version: 2.15.0
