redisPassword: Hc@Cloud01
#encodePassword: SGNAQ2xvdWQwMQ==
args:
  maxmemory-policy: volatile-lru
  renameCommand:
    # - CONFIG ""
    # - SHUTDOWN ""
    - KEYS NOKEYS
    - FLUSHDB ""
    - FLUSHALL ""

additionArgs: {}

storageSize: 5Gi
#storageClassName: default

# Redis version sets 7.2.8 by default, Optional versions are 6.2.18, 6.2.16, 7.2.8, 7.2.4, 7.0.12, 7.0.15
version: "7.2.8"
# sentinel/cluster
type: sentinel

image:
  repository: harbor.middleware.com/middleware
  logrotateImageTag: 3.21.0-1.0.0
  pullPolicy: IfNotPresent
  redisImageTag: 5.0.8-1.1.1
  redisImageTag_6: 6.2.6-1.2.0
  redisImageTag_6_11: 6.2.11-1.2.0
  redisImageTag_6_2_14: 6.2.14-1.2.0
  redisImageTag_6_2_16: 6.2.16-1.0.0
  redisImageTag_6_2_18: 6.2.18-1.0.0
  redisImageTag_7_0_12: 7.0.12-1.2.0
  redisImageTag_7_0_15: 7.0.15
  redisImageTag_7_2_4: 7.2.4-1.2.0
  redisImageTag_7_2_8: 7.2.8-1.0.0
  exporterImageTag: v1.0.5-1.0.0
  initImageTag: "v1.7.3"
  testImageTag: v0.3
  predixyImageTag: v1.0.3-1.0.0
  predixyExporterImageTag: v0.0.2-1.0.0

# 支持扩展spec
statefulSetConfiguration: {}
sentinelConfiguration: {}

nameOverride: ""
fullnameOverride: ""

# 升级方式
updateStrategy:
  type: AutoReceive

# global const environment variables for all redis, proxy, sentinel, exporter containers.
env:
  TZ: Asia/Shanghai

# global host volume mappings(host to container) for specific containers
hostVolumes: []
#- name: localtime
#  hostPath:
#    path: /usr/share/zoneinfo/Asia/Shanghai
#  volumeTargets:
#  - containerName: redis-cluster
#    mountPath: /etc/localtime
#  - containerName: sentinel
#    mountPath: /etc/localtime
#  - containerName: redis-exporter
#    mountPath: /etc/localtime
#  - containerName: predixy
#    mountPath: /etc/localtime

redis:
  externalAccess: {}
  #    enabled: false
  #    addresses:
  #      redis-0: 10.10.102.125:30421
  #      redis-1: 10.10.102.125:30607
  #      redis-2: 10.10.102.125:30312
  #      redis-3: 10.10.102.125:31087
  #      redis-4: 10.10.102.125:30719
  #      redis-5: 10.10.102.125:32205
  #    busPorts:
  #      redis-0: 32016
  #      redis-1: 32002
  #      redis-2: 30783
  #      redis-3: 31525
  #      redis-4: 30271
  #      redis-5: 30450
  #   sentinelAddresses:
  #      redis-sentinel-0: 10.10.102.125:31455
  #      redis-sentinel-1: 10.10.102.125:30507
  #      redis-sentinel-2: 10.10.102.125:30955
  command: /bin/launch.sh
  securityContext: {}
  #    runAsUser: 1000
  replicas: 6
  hostNetwork: false
  port: 6379
  # specific Affinity rules for redis pods and predixy pods.
  # if set, it will override the golbal affinity rules.
  nodeAffinity: {}
  topologyKey: ""
  resources:
    limits:
      cpu: "0.2"
      memory: 512Mi
    requests:
      cpu: "0.2"
      memory: 512Mi

sentinel:
  # deployMethod, default is deployment, optional values are statefulset,
  # if you want to expose sentinel pods ip, in externalAccess,
  # you should set deployMethod to statefulset.

  #  deployMethod: statefulset
  command: /bin/launch.sh
  args: {}
  #   down-after-milliseconds: "1000"
  #   failover-timeout: "3000"
  securityContext: {}
  #    runAsUser: 1000
  replicas: 3
  hostNetwork: false
  port: 26379
  # specific deployment update strategy for sentinel pods.
  # if set, it will override the default updateStrategy.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

exporter:
  port: 9121
  sentinelPort: 9121 # exporter port in sentinel
  rdbScan: {}
  # rdbScan configuration
  #  enable: true
  #  interval: 10
  #  bigKeyLen: 5
  #  bigKeyThreshold: 1000

# Global node affinity rules for all pods.
nodeAffinity: {}
# Global pod topologKey rules for all pods.
# if k8s version is >= 1.19, this field is set in topologySpreadConstraints field.
# if k8s version is < 1.19, this field is set in podAntiAffinity field.
podAntiAffinityTopologKey: "kubernetes.io/hostname"

tolerations: []
#- key: "example-key"
#  operator: "Exists"
#  effect: "NoSchedule"

annotations: {}

labels: {}

#取值[hard|soft] hard:强制反亲和 soft:非强制反亲和
podAntiAffinity: "soft"

predixy:
  args: {}
  #    master-read-priority: "90"
  #    static-slave-read-priority: "50"
  #    dynamic-slave-read-priority: "50"
  #    refresh-interval: "1"
  #    server-timeout: "1"
  #    server-failure-limit: "10"
  #    server-retry-timeout: "1"
  #    keep-alive: "120"
  securityContext: {}
  #    runAsUser: 1000
  enableProxy: false
  hostNetwork: false
  port: 7617
  exporterPort: 9121
  replicas: 1
  # specific deployment update strategy for predixy pods.
  # if set, it will override the default updateStrategy.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 512Mi
  exporterResources:
    requests:
      cpu: 25m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 100Mi

clusterMultiSts:
  shards: 3
  replicas: 2
  scheduler: "default-scheduler"

# just define logs
customVolumes: {}
#  - name: redis-data
#    mountPath: /redis/data
#    targetContainers:
#      - redis-cluster
#    storageClass: middleware-lvm
#    volumeSize: 1G
#    hostPath: /host/path
#  - name: redis-logs
#    mountPath: /redis/logs
#    targetContainers:
#      - redis-cluster
#    storageClass: middleware-lvm
#    volumeSize: 1G
