redis:
  replicas: 6
  resources:
    limits:
      cpu: "0.2"
      memory: 512Mi
    requests:
      cpu: "0.2"
      memory: 512Mi

sentinel:
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

storageSize: 5G