apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: redis-credential
spec:
  template: |
    apiVersion: v1
    stringData:
      endpoint: {{ .Globe.Name }}.{{ .Globe.Namespace }}.svc
      port: "{{ default .Values.redis.port .Values.redisServicePort }}"
      {{- if .Values.encodePassword }}
      password: "{{ (b64dec .Values.encodePassword) | default .Values.redisPassword }}"
      {{- else }}
      password: "{{ .Values.redisPassword }}"
      {{- end }}
    kind: Secret
    metadata:
      name: {{ .Globe.Name }}-credential
      namespace: {{ .Globe.Namespace }}
    type: Opaque
