apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: redis-datasecurity
  annotations:
    alias: "datasecurity"
    ignore: "true"
spec:
  baselineType: "NormalAction"
  actionType: "datasecurity"
  necessary:
  steps: