apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: pre-redis-heimdallr-hdpool
spec:
  baselineType: "PreAction"
  actionType: "hdpool"
  necessary:
    networkCardList: []
    annotations: {}
  steps:
    - name: hdpool
      type: "KubectlEdit" # KubectlGet、KubectlEdit、KubectlExec、Exec、HTTP
      cue: |
        output: {
          spec: parameters.spec
        }
        parameters: {
          spec: {
            parameters: {
              {{- if .Necessary.annotations }}
              statefulset: {
                spec: {
                  template: {
                    {{- with .Necessary.annotations }}
                    metadata: {
                      annotations: {{ toCue . }}
                    }
                    {{- end }}
                  }
                }
              }
              deployment: {
                spec: {
                  template: {
                    {{- with .Necessary.annotations }}
                    metadata: {
                      annotations: {{ toCue . }}
                    }
                    {{- end }}  
                  }
                }
              }
              {{- if hasKey .Parameters "predixy" }}
              predixy: {
                {{- with .Necessary.annotations }}
                annotations: {{ toCue . }}
                {{- end }}
              }
              {{- end }}
              {{- end }}
            }
          }
          resource: {
            apiversion: "middleware.cn/v1"
            kind: "Middleware"
            name: "{{ .Globe.Name }}"
            namespace: "{{ .Globe.Namespace }}"
          }
        }