apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: redis-restart
spec:
  baselineType: "NormalAction"
  actionType: "restart"
  necessary: {}
  steps:
    - name: isPredixy
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - "kubectl"
          - "get"
          - "rec"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "{{ .Globe.MiddlewareName }}"
          - "-o"
          - "jsonpath='{.spec.predixy}'"
          - "|"
          - "awk"
          - '''/image/ {found=1; exit} END {if (found) print "predixy"; else print ""}'''
    - name: restart
      cmd:
        command:
          - "kubectl"
          - "patch"
          - "redisCluster"
          - "{{ .Globe.MiddlewareName }}"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "--type=merge"
          - "-p"
          - '''{"metadata":{"annotations":{"middleware.maintenance.lock":"graceful-restart"}}}'''
    - name: waitForReady
      output:
        type: "string"
        expose: false
      cmd:
        command:
          - '{{ if eq .Step.isPredixy.output "predixy" }}i=0; while [ $i -lt 60 ] && kubectl get redisCluster -n {{ .Globe.Namespace }} {{ .Globe.MiddlewareName }} -o yaml 2>/dev/null | grep -q "middleware.maintenance.lock:"; do i=$((i+1)); echo "第 $i 次检查，维护锁存在"; sleep 10; done; echo "完成"{{ else }}echo 1{{ end }}'
    - name: restartPredixy
      cmd:
        command:
          - '{{ if eq .Step.isPredixy.output "predixy" }}kubectl annotate redisCluster -n {{ .Globe.Namespace }} {{ .Globe.MiddlewareName }} middleware.maintenance.lock=graceful-restart middleware.maintenance.component=predixy -overwrite=true{{ else }}echo 1{{ end }}'