apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: redis-set-parameters
  annotations:
    alias: "Middleware Set Parameters"
spec:
  baselineType: "NormalAction"
  actionType: "setParameters"
  necessary:
    parameters:
      - key: "test1"
        value: "test1"
      - key: "test2"
        value: "test2"
  steps:
    # 除去哨兵和代理
    - name: getPodNames
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - "kubectl"
          - "get"
          - "mid"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "{{ .Globe.MiddlewareName }}"
          - "-o"
          - '{{`go-template=''{{range .status.customResources.include.pods}}{{if and (ne .type "proxy") (ne .type "sentinel")}}{{.name}} {{end}}{{end}}''`}}'
    - name: getPassword
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - "kubectl"
          - "get"
          - "mid"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "{{ .Globe.MiddlewareName }}"
          - "-o"
          - 'jsonpath=''{.spec.necessary.password}'''
    - name: isProxy
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - |
            {{- $podNames := splitList " " .Step.getPodNames.output }}
            # 把参数拼接为 set globe key1 value1;set globe key2 value2;...
            {{- $setParametersString := "" }}
            {{- range $param := .Necessary.parameters }}
            {{- $setParametersString = printf "redis-cli -h 127.0.0.1 -p 6379 -a {{ $.Step.getPassword.output }} config set %s '%s' ;" $setParametersString (index $param "key") (index $param "value") }}
            {{- end }}
            {{- range $podName := $podNames }}
            kubectl exec {{ $podName }} -n {{ $.Globe.Namespace }} -c redis-cluster -- bash -c '{{ $setParametersString }}'
            {{- end }}