apiVersion: middleware.cn/v1
kind: MiddlewareBaseline
metadata:
  name: redis-cluster-proxy
  labels:
    nephele/user: admin
  annotations:
    datapath: '{{ printf "/data/redis/cluster.local/%s/%s/{POD_NAME}/data" .Globe.Namespace .Globe.Name }}'
    baselineName: "Cluster Proxy Mode"
    description: "Cluster Proxy Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
spec:
  operatorBaseline:
    name: redis-operator-standard
    gvkName: v1alpha1
  necessary:
    repository: ""
    version: '{"type":"version","label":"Version","required":true,"default":"8.2.3"}'
    password: |
      {
        "type": "password",
        "label": "AdminPassword",
        "required": true,
        "description": "Please enter a password consisting of English letters, numbers, or the special characters \"/, ~, %, _, .\", with a length between 1 and 32 characters.",
        "placeholder": "Enter your admin password",
        "pattern": "^[A-Za-z0-9~_./%]{1,32}$"
       }
    resource:
      redis:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core","placeholder":"Please enter a custom quota, the unit is `Core","default":"1","pattern":"^(?!0$)(?!0\\d)\\d+(\\.\\d)?$","min":0.1}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4","pattern":"^(?!0$)(?!0\\d)\\d+(\\.\\d)?$","min":0.1}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core","placeholder":"Please enter a custom quota, the unit is `Core","default":"1","pattern":"^(?!0$)(?!0\\d)\\d+(\\.\\d)?$","min":0.1}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4","pattern":"^(?!0$)(?!0\\d)\\d+(\\.\\d)?$","min":0.1}'
        replicas: '{"type":"int","label":"Replicas","required":true,"description":"Minimum number of shards is 3","default":6,"pattern":"^[1-9]\\d*$","placeholder":"Please enter the number of instances"}'
        volume:
          size: '{"type":"int","label":"StorageSize","required":true,"pattern":"^(?!0$)(?!0\\d)\\d+(\\.\\d)?$","placeholder":"Please enter the storage size"}'
          storageClass: '{"type":"storageClass","label":"StorageClass","required":true,"description":"Please select storage","placeholder":"Please select storage"}'
      predixy:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core","placeholder":"Please enter a custom quota, the unit is `Core","default":"1","pattern":"^(?!0$)(?!0\\d)\\d+(\\.\\d)?$","min":0.1}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4","pattern":"^(?!0$)(?!0\\d)\\d+(\\.\\d)?$","min":0.1}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core","placeholder":"Please enter a custom quota, the unit is `Core","default":"1","pattern":"^(?!0$)(?!0\\d)\\d+(\\.\\d)?$","min":0.1}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4","pattern":"^(?!0$)(?!0\\d)\\d+(\\.\\d)?$","min":0.1}'
  preActions:
    - name: pre-redis-heimdallr-hdpool
      parameters:
        networkCardList: []
        annotations: {}
      fixed: false
      exposed: true
    - name: pre-redis-alertrule-labels
      parameters:
        labels: {}
      exposed: false
    - name: pre-redis-logging
      parameters:
        fileLogging: true
        stdoutLogging: true
      fixed: false
      exposed: true
    - name: pre-redis-tolerations
      parameters:
        tolerations: [ ]
      fixed: false
      exposed: true
    - name: pre-redis-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: { }
      fixed: false
      exposed: true
    # - name: pre-redis-proxy-affinity
    #   parameters:
    #     podAntiAffinityTopologKey: "kubernetes.io/hostname"
    #     podAntiAffinity: "soft"
    #     nodeAffinity: { }
    #   fixed: false
    #   exposed: true
  parameters:
    env:
      TZ: Asia/Shanghai
    type: cluster
    predixy:
      image: "predixy:v1.0.4"
      exporterImage: "predixy-exporter:v0.0.2-1.0.0"
      affinity:
      args: { }
      enableProxy: true
      exporterPort: 9121
      exporterResources:
        limits:
          cpu: 50m
          memory: 100Mi
        requests:
          cpu: 25m
          memory: 50Mi
      hostNetwork: false
      port: 7617
      replicas: 3
      resources:
        requests:
          cpu: '"{{ .Necessary.resource.predixy.requests.cpu }}"'
          memory: '"{{ .Necessary.resource.predixy.requests.memory }}"'
        limits:
          cpu: '"{{ .Necessary.resource.predixy.limits.cpu }}"'
          memory: '"{{ .Necessary.resource.predixy.limits.memory }}"'
      securityContext: { }
      strategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
    pod:
      - affinity:
        annotations:
          fixed-node-middleware-pod: "true"
          fixed.ipam.harmonycloud.cn: "true"
        configmap: "{{ .Globe.Name }}-config"
        env:
          - name: SYS_CODE
            value: "{{ .Globe.Name }}"
        labels:
          harmonycloud.cn/statefulset: "{{ .Globe.Name }}"
          middleware: redis
          nephele/user: admin
        middlewareImage: '"{{- $v := .Necessary.version -}}
  {{- $mid := "port" -}}
  {{- $suffix := "-1.0.0" -}}
  {{- if eq $v "5.0.8" }}{{ $mid = "v5-port" }}{{ $suffix = "-1.1.1" -}}
  {{- else if hasPrefix "6.2." $v }}
    {{- if le $v "6.2.18" }}{{ $mid = "v6-port" }}{{ end -}}
    {{- if le $v "6.2.14" }}{{ $suffix = "-1.2.0" }}{{ end -}}
  {{- else if or (hasPrefix "7.0." $v) (hasPrefix "7.2." $v) }}
    {{- if le $v "7.2.8" }}{{ $mid = "v7-port" }}{{ end -}}
    {{- if or (eq $v "7.0.12") (eq $v "7.2.4") }}{{ $suffix = "-1.2.0" }}{{ end -}}
  {{- else if eq $v "8.2.2" }}{{ $v = (printf "v%s" $v) }}{{ $suffix = "-1.0.0-redis" -}}
  {{- else if eq $v "8.2.3" }}{{ $suffix = "" -}}
  {{- end -}}
  {{- printf "redis-cli-%s:%s%s" $mid $v $suffix -}}"'
        initImage: "redis-init:v1.7.4"
        monitorImage: "redis-exporter:v1.0.5-1.1.0"
        logrotateImage: "logrotate:3.21.0-1.0.0"
        requirepass: "{{ .Necessary.password }}"
        imagePullPolicy: IfNotPresent
        hostNetwork: false
        resources:
          limits:
            cpu: '"{{ .Necessary.resource.redis.limits.cpu }}"'
            memory: '"{{ .Necessary.resource.redis.limits.memory }}"'
          requests:
            cpu: '"{{ .Necessary.resource.redis.requests.cpu }}"'
            memory: '"{{ .Necessary.resource.redis.requests.memory }}"'
        updateStrategy: { }
        command: /bin/launch.sh
    exporter:
      port: 9121
      sentinelPort: 9121
      hotKeyScan:
        enable: true
        interval: 3600
        hotkeyThreshold: 2
        hotKeylen: 100
      rdbScan:
        enable: true
        interval: 3600
        bigKeyThreshold: 1024
        bigKeyLen: 100
        filePath: "/data/redis/cluster.local/{{ .Globe.Namespace }}/{{ .Globe.Name }}/{POD_NAME}/data"
      envs:
      - name: "REDIS_EXPORTER_SLOWLOG_ENABLED"
        value: "true"
      - name: "REDIS_EXPORTER_SLOWLOG_LIMIT"
        value: "100"
    podManagementPolicy: Parallel
    replicas: "{{ .Necessary.resource.redis.replicas }}"
    servicePort: 6379
    repository: "{{ .Necessary.repository }}/"
    updateStrategy:
      type: AutoReceive
    version: "{{ .Necessary.version }}"
    volumeClaimTemplates:
      - metadata:
          name: redis-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "{{ .Necessary.resource.redis.volume.storageClass }}"
          resources:
            requests:
              storage: '"{{ .Necessary.resource.redis.volume.size }}"'
  configurations:
    - name: redis-credential
      values:
        redis:
          port: "{{ .Parameters.servicePort }}"
        redisPassword: "{{ (index .Parameters.pod 0).requirepass }}"
    - name: redis-predixy-servicemonitor
      values:
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
    - name: redis-alertrule
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
        alertRules:
          MismatchedRequestResponseRate: { }
          RedisExporterDown: { }
          RedisFailOver: { }
          RedisUnhealthy: { }
          RedisLargConnect: { }
          RedisLargeBlockConnect: { }
          RedisReplicationBroken: { }
          RedisOutOfConfiguredMaxmemory: { }
          RedisVolumeUsageMinor: { }
          RedisVolumeUsageMajor: { }
          RedsMemoryUsageHigh: { }
          RedisCpuUsageHigh: { }
          RedisSentinelWatchNodeUnhealthy: { }
          RedisSentries_num: { }
    - name: redis-config
      values:
        redis:
          resources:
            limits:
              cpu: '"{{ .Necessary.resource.redis.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.redis.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.redis.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.redis.requests.memory }}"'
        type: "{{ .Parameters.type }}"
        version: "{{ .Parameters.version }}"
        customVolumes: { }
        additionArgs: { }
        args:
          maxmemory-policy: volatile-lru
          renameCommand:
            # - CONFIG ""
            # - SHUTDOWN ""
            - KEYS NOKEYS
            - FLUSHDB ""
            - FLUSHALL ""
    - name: redis-sc
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
    - name: redis-servicemonitor
    - name: redis-shard-sc
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
        redis:
          replicas: "{{ .Necessary.resource.redis.replicas }}"
    - name: redis-predixy-configmap
      values:
        redis:
          port: 6379
          replicas: "{{ .Necessary.resource.redis.replicas }}"
        sentinel:
          port: 26379
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
          port: 7617
#          workerThreads:
          args: {}
#            client-timeout:
#            buf-size:
#            max-memory:
#            master-read-priority:
#            static-slave-read-priority:
#            dynamic-slave-read-priority:
#            refresh-interval:
#            server-timeout:
#            server-failure-limit:
#            server-retry-timeout:
#            keep-alive:
        redisPassword: "{{ (index .Parameters.pod 0).requirepass }}"
        type: "cluster"