apiVersion: middleware.cn/v1
kind: MiddlewareBaseline
metadata:
  name: redis-cluster-proxy
  labels:
    nephele/user: admin
  annotations:
    datapath: '{{ printf "/data/redis/cluster.local/%s/%s/{POD_NAME}/data" .Globe.Namespace .Globe.Name }}'
    baselineName: "集群代理模式"
    description: "集群代理模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
spec:
  operatorBaseline:
    name: redis-operator-standard
    gvkName: v1alpha1
  necessary:
    repository: ""
    version: '{"type":"version","label":"版本","required":true,"default":"7.2.8"}'
    password: '{"type":"password","label":"管理员账号密码","required":true,"description":"管理员的初始密码","placeholder":"输入管理员账户密码","default":"Hc@Cloud01"}'
    resource:
      redis:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        replicas: '{"type":"int","label":"实例数","required":true,"description":"节点数量","default":1,"pattern":"^[1-9]\\d*$","placeholder":"请输入实例数"}'
        volume:
          size: '{"type":"int","label":"存储大小","required":true,"description":"请输入存储大小","pattern":"^[1-9]\\d*$","placeholder":"请输入存储大小"}'
          storageClass: '{"type":"storageClass","label":"存储类","required":true,"description":"请选择存储","placeholder":"请选择存储"}'
      predixy:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
  preActions:
    - name: pre-redis-alertrule-labels
      parameters:
        labels: {}
      exposed: false
    - name: pre-redis-logging
      parameters:
        fileLogging: true
        stdoutLogging: true
      fixed: false
      exposed: true
    - name: pre-redis-tolerations
      parameters:
        tolerations: [ ]
      fixed: false
      exposed: true
    - name: pre-redis-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: { }
      fixed: false
      exposed: true
    # - name: pre-redis-proxy-affinity
    #   parameters:
    #     podAntiAffinityTopologKey: "kubernetes.io/hostname"
    #     podAntiAffinity: "soft"
    #     nodeAffinity: { }
    #   fixed: false
    #   exposed: true
  parameters:
    env:
      TZ: Asia/Shanghai
    type: cluster
    predixy:
      image: "predixy:v1.0.3-1.0.0"
      exporterImage: "predixy-exporter:v0.0.2-1.0.0"
      affinity:
      args: { }
      enableProxy: true
      exporterPort: 9121
      exporterResources:
        limits:
          cpu: 50m
          memory: 100Mi
        requests:
          cpu: 25m
          memory: 50Mi
      hostNetwork: false
      port: 7617
      replicas: 3
      resources:
        requests:
          cpu: '"{{ .Necessary.resource.predixy.requests.cpu }}"'
          memory: '"{{ .Necessary.resource.predixy.requests.memory }}"'
        limits:
          cpu: '"{{ .Necessary.resource.predixy.limits.cpu }}"'
          memory: '"{{ .Necessary.resource.predixy.limits.memory }}"'
      securityContext: { }
      strategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
    pod:
      - affinity:
        annotations:
          fixed-node-middleware-pod: "true"
          fixed.ipam.harmonycloud.cn: "true"
        configmap: "{{ .Globe.Name }}-config"
        env:
          - name: SYS_CODE
            value: "{{ .Globe.Name }}"
        labels:
          harmonycloud.cn/statefulset: "{{ .Globe.Name }}"
          middleware: redis
          nephele/user: admin
        middlewareImage: '{{ if eq .Necessary.version "5.0.8" }}redis-cli-v5-port:5.0.8-1.1.1{{ else if eq .Necessary.version "6.2.6" }}redis-cli-v6-port:6.2.6-1.2.0{{ else if eq .Necessary.version "6.2.11" }}redis-cli-v6-port:6.2.11-1.2.0{{ else if eq .Necessary.version "6.2.14" }}redis-cli-v6-port:6.2.14-1.2.0{{ else if eq .Necessary.version "6.2.16" }}redis-cli-v6-port:6.2.16-1.0.0{{ else if eq .Necessary.version "6.2.18" }}redis-cli-v6-port:6.2.18-1.0.0{{ else if eq .Necessary.version "7.0.12" }}redis-cli-v7-port:7.0.12-1.2.0{{ else if eq .Necessary.version "7.0.15" }}redis-cli-v7-port:7.0.15{{ else if eq .Necessary.version "7.2.4" }}redis-cli-v7-port:7.2.4-1.2.0{{ else if eq .Necessary.version "7.2.8" }}redis-cli-v7-port:7.2.8-1.0.0{{ else if eq .Necessary.version "6.2.19" }}redis-cli-port:6.2.19-1.0.0{{ else if eq .Necessary.version "7.2.10" }}redis-cli-port:7.2.10-1.0.0{{ else if eq .Necessary.version "7.4.5" }}redis-cli-port:7.4.5-1.0.0{{ else if eq .Necessary.version "8.0.3" }}redis-cli-port:8.0.3-1.0.0{{ end }}'
        initImage: "redis-init:v1.7.4"
        monitorImage: "redis-exporter:v1.0.5-1.0.1"
        logrotateImage: "logrotate:3.21.0-1.0.0"
        requirepass: "{{ .Necessary.password }}"
        imagePullPolicy: IfNotPresent
        hostNetwork: false
        resources:
          limits:
            cpu: '"{{ .Necessary.resource.redis.limits.cpu }}"'
            memory: '"{{ .Necessary.resource.redis.limits.memory }}"'
          requests:
            cpu: '"{{ .Necessary.resource.redis.requests.cpu }}"'
            memory: '"{{ .Necessary.resource.redis.requests.memory }}"'
        updateStrategy: { }
        command: /bin/launch.sh
    exporter:
      port: 9121
      rdbScan: { }
      sentinelPort: 9121
    podManagementPolicy: Parallel
    replicas: "{{ .Necessary.resource.redis.replicas }}"
    servicePort: 6379
    repository: "{{ .Necessary.repository }}/"
    updateStrategy:
      type: AutoReceive
    version: "7.2.8"
    volumeClaimTemplates:
      - metadata:
          name: redis-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "{{ .Necessary.resource.redis.volume.storageClass }}"
          resources:
            requests:
              storage: '"{{ .Necessary.resource.redis.volume.size }}"'
  configurations:
    - name: redis-credential
      values:
        redis:
          port: "{{ (index .Parameters.pod 0).servicePort }}"
        redisPassword: "{{ (index .Parameters.pod 0).requirepass }}"
    - name: redis-predixy-servicemonitor
      values:
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
    - name: redis-alertrule
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
    - name: redis-config
      values:
        type: "{{ .Parameters.type }}"
        version: "{{ .Parameters.version }}"
        customVolumes: { }
        additionArgs: { }
        args:
          maxmemory-policy: volatile-lru
          renameCommand:
            # - CONFIG ""
            # - SHUTDOWN ""
            - KEYS NOKEYS
            - FLUSHDB ""
            - FLUSHALL ""
    - name: redis-sc
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
    - name: redis-servicemonitor
    - name: redis-shard-sc
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
        redis:
          replicas: "{{ .Necessary.resource.redis.replicas }}"
