apiVersion: middleware.cn/v1
kind: MiddlewareBaseline
metadata:
  name: redis-cluster
  labels:
    nephele/user: admin
  annotations:
    datapath: '{{ printf "/data/redis/cluster.local/%s/%s/{POD_NAME}/data" .Globe.Namespace .Globe.Name }}'
    baselineName: "集群模式"
    description: "集群模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
spec:
  operatorBaseline:
    name: redis-operator-standard
    gvkName: v1alpha1
  necessary:
    repository: ""
    version: '{"type":"version","label":"版本","required":true,"default":"8.0.4"}'
    password: |
      {
        "type": "password",
        "label": "管理员账号密码",
        "required": true,
        "description": "请输入由英文字母、数字或特殊字符“/、~、%、_、.”组成的密码信息",
        "placeholder": "输入管理员账户密码",
        "default": "Hc@Cloud01",
        "pattern": "^[^!&|;$\\'\"><*?`(){}@#]*$"
       }
    resource:
      redis:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"2"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"2"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        replicas: '{"type":"int","label":"实例数","required":true,"description":"分片数，最小为三分片","default":6,"pattern":"^[1-9]\\d*$","placeholder":"请输入实例数"}'
        volume:
          size: '{"type":"int","label":"存储大小","required":true,"description":"存储大小最低为1","pattern":"^[1-9]\\d*$","placeholder":"请输入存储大小"}'
          storageClass: '{"type":"storageClass","label":"存储类","required":true,"description":"请选择存储","placeholder":"请选择存储"}'
  preActions:
    - name: pre-redis-heimdallr-hdpool
      parameters:
        networkCardList: []
        annotations: {}
      fixed: false
      exposed: true
    - name: pre-redis-alertrule-labels
      parameters:
        labels: {}
      exposed: false
    - name: pre-redis-logging
      parameters:
        fileLogging: true
        stdoutLogging: true
      fixed: false
      exposed: true
    - name: pre-redis-tolerations
      parameters:
        tolerations: [ ]
      fixed: false
      exposed: true
    - name: pre-redis-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: { }
      fixed: false
      exposed: true
  parameters:
    env:
      TZ: Asia/Shanghai
    type: cluster
    pod:
      - affinity:
        annotations:
          fixed-node-middleware-pod: "true"
          fixed.ipam.harmonycloud.cn: "true"
        configmap: "{{ .Globe.Name }}-config"
        env:
          - name: SYS_CODE
            value: "{{ .Globe.Name }}"
        labels:
          harmonycloud.cn/statefulset: "{{ .Globe.Name }}"
          middleware: redis
          nephele/user: admin
        middlewareImage: |
          {{- define "middleware.image" -}}
          {{- $version := .Necessary.version -}}
          {{- $versionMap := dict -}}
          {{- $_ := set $versionMap "5.0.8" (printf "redis-cli-v5-port:%s" "5.0.8-1.1.1") -}}
          {{- $_ := set $versionMap "6.2.6" (printf "redis-cli-v6-port:%s" "6.2.6-1.2.0") -}}
          {{- $_ := set $versionMap "6.2.11" (printf "redis-cli-v6-port:%s" "6.2.11-1.2.0") -}}
          {{- $_ := set $versionMap "6.2.14" (printf "redis-cli-v6-port:%s" "6.2.14-1.2.0") -}}
          {{- $_ := set $versionMap "6.2.16" (printf "redis-cli-v6-port:%s" "6.2.16-1.0.0") -}}
          {{- $_ := set $versionMap "6.2.18" (printf "redis-cli-v6-port:%s" "6.2.18-1.0.0") -}}
          {{- $_ := set $versionMap "6.2.19" (printf "redis-cli-port:%s" "6.2.19-1.0.0") -}}
          {{- $_ := set $versionMap "6.2.20" (printf "redis-cli-port:%s" "6.2.20-1.0.0") -}}
          {{- $_ := set $versionMap "7.0.12" (printf "redis-cli-v7-port:%s" "7.0.12-1.2.0") -}}
          {{- $_ := set $versionMap "7.0.15" (printf "redis-cli-v7-port:%s" "7.0.15-1.0.0") -}}
          {{- $_ := set $versionMap "7.2.4" (printf "redis-cli-v7-port:%s" "7.2.4-1.2.0") -}}
          {{- $_ := set $versionMap "7.2.8" (printf "redis-cli-v7-port:%s" "7.2.8-1.0.0") -}}
          {{- $_ := set $versionMap "7.2.10" (printf "redis-cli-port:%s" "7.2.10-1.0.0") -}}
          {{- $_ := set $versionMap "7.2.11" (printf "redis-cli-port:%s" "7.2.11-1.0.0") -}}
          {{- $_ := set $versionMap "7.4.5" (printf "redis-cli-port:%s" "7.4.5-1.0.0") -}}
          {{- $_ := set $versionMap "7.4.6" (printf "redis-cli-port:%s" "7.4.6-1.0.0") -}}
          {{- $_ := set $versionMap "8.0.3" (printf "redis-cli-port:%s" "8.0.3-1.0.0") -}}
          {{- $_ := set $versionMap "8.0.4" (printf "redis-cli-port:%s" "8.0.4-1.0.0") -}}
          {{- $middlewareImage := index $versionMap $version | default "" -}}
          {{- $middlewareImage -}}
          {{- end -}}
          {{- include "middleware.image" . | quote -}}
        initImage: "redis-init:v1.7.4"
        monitorImage: "redis-exporter:v1.0.5-1.1.0"
        logrotateImage: "logrotate:3.21.0-1.0.0"
        requirepass: "{{ .Necessary.password }}"
        imagePullPolicy: IfNotPresent
        hostNetwork: false
        resources:
          limits:
            cpu: '"{{ .Necessary.resource.redis.limits.cpu }}"'
            memory: '"{{ .Necessary.resource.redis.limits.memory }}"'
          requests:
            cpu: '"{{ .Necessary.resource.redis.requests.cpu }}"'
            memory: '"{{ .Necessary.resource.redis.requests.memory }}"'
        updateStrategy: { }
        command: /bin/launch.sh
    exporter:
      port: 9121
      rdbScan: { }
      sentinelPort: 9121
      hotKeyScan:
        enable: true
        interval: 3600
        hotkeyThreshold: 2
        hotKeylen: 100
      rdbScan:
        enable: true
        interval: 3600
        bigKeyThreshold: 1024
        bigKeyLen: 100
        filePath: "/data/redis/cluster.local/{{ .Globe.Namespace }}/{{ .Globe.Name }}/{POD_NAME}/data"
      envs:
      - name: "REDIS_EXPORTER_SLOWLOG_ENABLED"
        value: "true"
      - name: "REDIS_EXPORTER_SLOWLOG_LIMIT"
        value: "100"
    podManagementPolicy: Parallel
    replicas: "{{ .Necessary.resource.redis.replicas }}"
    servicePort: 6379
    repository: "{{ .Necessary.repository }}/"
    updateStrategy:
      type: AutoReceive
    version: "{{ .Necessary.version }}"
    volumeClaimTemplates:
      - metadata:
          name: redis-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "{{ .Necessary.resource.redis.volume.storageClass }}"
          resources:
            requests:
              storage: '"{{ .Necessary.resource.redis.volume.size }}"'
  configurations:
    - name: redis-credential
      values:
        redis:
          port: "{{ (index .Parameters.pod 0).servicePort }}"
        redisPassword: "{{ (index .Parameters.pod 0).requirepass }}"
    - name: redis-predixy-servicemonitor
      values:
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
    - name: redis-alertrule
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
        alertRules:
          MismatchedRequestResponseRate: { }
          RedisExporterDown: { }
          RedisFailOver: { }
          RedisUnhealthy: { }
          RedisLargConnect: { }
          RedisLargeBlockConnect: { }
          RedisReplicationBroken: { }
          RedisOutOfConfiguredMaxmemory: { }
          RedisVolumeUsageMinor: { }
          RedisVolumeUsageMajor: { }
          RedsMemoryUsageHigh: { }
          RedisCpuUsageHigh: { }
          RedisSentinelWatchNodeUnhealthy: { }
          RedisSentries_num: { }
    - name: redis-config
      values:
        redis:
          resources:
            limits:
              cpu: '"{{ .Necessary.resource.redis.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.redis.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.redis.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.redis.requests.memory }}"'
        type: "{{ .Parameters.type }}"
        version: "{{ .Necessary.version }}"
        customVolumes: { }
        additionArgs: { }
        args:
          maxmemory-policy: volatile-lru
          renameCommand:
            # - CONFIG ""
            # - SHUTDOWN ""
            - KEYS NOKEYS
            - FLUSHDB ""
            - FLUSHALL ""
    - name: redis-sc
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
    - name: redis-servicemonitor
    - name: redis-shard-sc
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
        redis:
          replicas: "{{ .Necessary.resource.redis.replicas }}"
