apiVersion: middleware.cn/v1
kind: MiddlewareBaseline
metadata:
  name: redis-sentinel-active
  labels:
    nephele/user: admin
  annotations:
    datapath: '{{ printf "/data/redis/cluster.local/%s/%s/{POD_NAME}/data" .Globe.Namespace .Globe.Name }}'
    baselineName: "哨兵模式-双活"
    description: "哨兵模式基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
    active: "2"
spec:
  operatorBaseline:
    name: redis-operator-standard
    gvkName: v1alpha1
  necessary:
    repository: ""
    version: '{"type":"version","label":"版本","required":true,"default":"8.0.4"}'
    password: |
      {
        "type": "password",
        "label": "管理员账号密码",
        "required": true,
        "description": "请输入由英文字母、数字或特殊字符“/、~、%、_、.”组成的密码信息",
        "placeholder": "输入管理员账户密码",
        "default": "Hc@Cloud01",
        "pattern": "^[^!&|;$\\'\"><*?`(){}@#]*$"
       }
    resource:
      redis:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        replicas: '{"type":"int","label":"实例数","required":true,"description":"分片数，最小为单分片","default":2,"pattern":"^[1-9]\\d*$","placeholder":"请输入实例数"}'
        volumes: ""
      sentinel:
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
        replicas: '{"type":"int","label":"实例数","required":true,"description":"当前输入的实例数不符合规范，实例数最低为1，请调整后再次提交","default":3,"pattern":"^[1-9]\\d*$","placeholder":"请输入实例数"}'
        deployMethod: |
          {
            "type": "enum",
            "label": "部署方式",
            "required": true,
            "default":"Deployment",
            "options": "无状态部署,有状态部署",
            "visible": true,
            "optionsMap": [
              {"label": "无状态部署", "value": "deployment"},
              {"label": "有状态部署", "value": "statefulset"}
            ]
          }
  preActions:
    - name: pre-redis-heimdallr-hdpool
      parameters:
        networkCardList: []
        annotations: {}
      fixed: false
      exposed: true
    - name: pre-redis-alertrule-labels
      parameters:
        labels: {}
      exposed: false
    - name: pre-redis-logging
      parameters:
        fileLogging: true
        stdoutLogging: true
      fixed: false
      exposed: true
    - name: pre-redis-tolerations
      parameters:
        tolerations: []
      fixed: false
      exposed: true
    - name: pre-redis-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: {}
      fixed: false
      exposed: true
    # - name: pre-redis-sentinel-affinity
    #   parameters:
    #     podAntiAffinityTopologKey: "kubernetes.io/hostname"
    #     podAntiAffinity: "soft"
    #     nodeAffinity: {}
    #   fixed: false
    #   exposed: true
  parameters:
    env:
      TZ: Asia/Shanghai
    type: sentinel
    sentinel:
      deployMethod: "{{ .Necessary.resource.sentinel.deployMethod }}"
      affinity:
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: REDIS_INSTANCE_PORT
          value: "26379"
        - name: TYPE
          value: "sentinel"
        - name: PODIP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - redis-cli -h $POD_IP -p 26379 ping
        timeoutSeconds: 5
      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - redis-cli -h $POD_IP -p 26379 ping
        timeoutSeconds: 5
      args: {}
      command: /bin/launch.sh
      hostNetwork: false
      port: 26379
      replicas: "{{ .Necessary.resource.sentinel.replicas }}"
      resources:
        requests:
          cpu: '"{{ .Necessary.resource.sentinel.requests.cpu }}"'
          memory: '"{{ .Necessary.resource.sentinel.requests.memory }}"'
        limits:
          cpu: '"{{ .Necessary.resource.sentinel.limits.cpu }}"'
          memory: '"{{ .Necessary.resource.sentinel.limits.memory }}"'
      securityContext: {}
      strategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
    pod:
      - affinity:
        annotations:
          fixed-node-middleware-pod: "true"
          fixed.ipam.harmonycloud.cn: "true"
        configmap: "{{ .Globe.Name }}-config"
        env:
          - name: SYS_CODE
            value: "{{ .Globe.Name }}"
        labels:
          harmonycloud.cn/statefulset: "{{ .Globe.Name }}"
          middleware: redis
          nephele/user: admin
        middlewareImage: '{{ if eq .Necessary.version "5.0.8" }}redis-cli-v5-port:5.0.8-1.1.1{{ else if eq .Necessary.version "6.2.6" }}redis-cli-v6-port:6.2.6-1.2.0{{ else if eq .Necessary.version "6.2.11" }}redis-cli-v6-port:6.2.11-1.2.0{{ else if eq .Necessary.version "6.2.14" }}redis-cli-v6-port:6.2.14-1.2.0{{ else if eq .Necessary.version "6.2.16" }}redis-cli-v6-port:6.2.16-1.0.0{{ else if eq .Necessary.version "6.2.18" }}redis-cli-v6-port:6.2.18-1.0.0{{ else if eq .Necessary.version "6.2.19" }}redis-cli-port:6.2.19-1.0.0{{ else if eq .Necessary.version "6.2.20" }}redis-cli-port:6.2.20-1.0.0{{ else if eq .Necessary.version "7.0.12" }}redis-cli-v7-port:7.0.12-1.2.0{{ else if eq .Necessary.version "7.0.15" }}redis-cli-v7-port:7.0.15-1.0.0{{ else if eq .Necessary.version "7.2.4" }}redis-cli-v7-port:7.2.4-1.2.0{{ else if eq .Necessary.version "7.2.8" }}redis-cli-v7-port:7.2.8-1.0.0{{ else if eq .Necessary.version "7.2.10" }}redis-cli-port:7.2.10-1.0.0{{ else if eq .Necessary.version "7.2.11" }}redis-cli-port:7.2.11-1.0.0{{ else if eq .Necessary.version "7.4.5" }}redis-cli-port:7.4.5-1.0.0{{ else if eq .Necessary.version "7.4.6" }}redis-cli-port:7.4.6-1.0.0{{ else if eq .Necessary.version "8.0.3" }}redis-cli-port:8.0.3-1.0.0{{ else if eq .Necessary.version "8.0.4" }}redis-cli-port:8.0.4-1.0.0{{ end }}'
        initImage: "redis-init:v1.7.4"
        monitorImage: "redis-exporter:v1.0.5-1.1.0"
        logrotateImage: "logrotate:3.21.0-1.0.0"
        requirepass: "{{ .Necessary.password }}"
        imagePullPolicy: IfNotPresent
        hostNetwork: false
        resources:
          limits:
            cpu: '"{{ .Necessary.resource.redis.limits.cpu }}"'
            memory: '"{{ .Necessary.resource.redis.limits.memory }}"'
          requests:
            cpu: '"{{ .Necessary.resource.redis.requests.cpu }}"'
            memory: '"{{ .Necessary.resource.redis.requests.memory }}"'
        updateStrategy: {}
        command: /bin/launch.sh
    exporter:
      port: 9121
      sentinelPort: 9121
      hotKeyScan:
        enable: true
        interval: 3600
        hotkeyThreshold: 2
        hotKeylen: 100
      rdbScan:
        enable: true
        interval: 3600
        bigKeyThreshold: 1024
        bigKeyLen: 100
        filePath: "/data/redis/cluster.local/{{ .Globe.Namespace }}/{{ .Globe.Name }}/{POD_NAME}/data"
      envs:
      - name: "REDIS_EXPORTER_SLOWLOG_ENABLED"
        value: "true"
      - name: "REDIS_EXPORTER_SLOWLOG_LIMIT"
        value: "100"
    podManagementPolicy: Parallel
    replicas: "{{ .Necessary.resource.redis.replicas }}"
    servicePort: 6379
    repository: "{{ .Necessary.repository }}/"
    updateStrategy:
      type: AutoReceive
    version: "{{ .Necessary.version }}"
    volumeClaimTemplates:
      - metadata:
          name: redis-data
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: '{{ range $i, $v := .Necessary.resource.redis.volumes }}{{ if $i }},{{ end }}{{ $v.storageClass }}{{ end }}'
          resources:
            requests:
              storage: '"{{ index .Necessary.resource.redis.volumes 0 "size" }}"'
  configurations:
    - name: redis-credential
      values:
        redis:
          port: "{{ .Parameters.servicePort }}"
        redisPassword: "{{ (index .Parameters.pod 0).requirepass }}"
    - name: redis-predixy-servicemonitor
      values:
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
    - name: redis-alertrule
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
        alertRules:
          MismatchedRequestResponseRate: { }
          RedisExporterDown: { }
          RedisFailOver: { }
          RedisUnhealthy: { }
          RedisLargConnect: { }
          RedisLargeBlockConnect: { }
          RedisReplicationBroken: { }
          RedisOutOfConfiguredMaxmemory: { }
          RedisVolumeUsageMinor: { }
          RedisVolumeUsageMajor: { }
          RedsMemoryUsageHigh: { }
          RedisCpuUsageHigh: { }
          RedisSentinelWatchNodeUnhealthy: { }
          RedisSentries_num: { }
    - name: redis-config
      values:
        redis:
          resources:
            limits:
              cpu: '"{{ .Necessary.resource.redis.limits.cpu }}"'
              memory: '"{{ .Necessary.resource.redis.limits.memory }}"'
            requests:
              cpu: '"{{ .Necessary.resource.redis.requests.cpu }}"'
              memory: '"{{ .Necessary.resource.redis.requests.memory }}"'
        type: "{{ .Parameters.type }}"
        version: "{{ .Parameters.version }}"
        customVolumes: {}
        additionArgs: {}
        args:
          maxmemory-policy: volatile-lru
          renameCommand:
            # - CONFIG ""
            # - SHUTDOWN ""
            - KEYS NOKEYS
            - FLUSHDB ""
            - FLUSHALL ""
    - name: redis-sc
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
    - name: redis-servicemonitor
    - name: redis-shard-sc
      values:
        type: "{{ .Parameters.type }}"
        predixy:
          enableProxy: '"{{ if hasKey .Parameters "predixy" }}true{{ else }}flase{{ end }}"'
        redis:
          replicas: "{{ .Necessary.resource.redis.replicas }}"
