{
 "title": "Redis Proxy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(redis_up, namespace)"
   },
   {
    "name": "redis",
    "label": "Redis cluster",
    "query": "query_result(kube_statefulset_labels{namespace=\"$namespace\", label_middleware=\"redis\"})"
   },
   {
    "name": "proxy",
    "label": "proxy",
    "query": "label_values(predixy_used_cpu{namespace=\"$namespace\", service=\"$redis\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$proxy\",endpoint!=\"\",container!=\"\"}[5m]) ) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$proxy\",resource=\"cpu\"}) by (pod)  * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Working Set Usage(%)",
   "type": "graph",
   "description": "The percentage of requested memory resources that are actually being used (memory working set bytes) by the proxy pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$proxy\",endpoint!=\"\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$proxy\",resource=\"memory\"}) by (pod) * 100",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "Recv Bytes",
   "type": "graph",
   "description": "display only when proxy is enabled.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(predixy_total_recv_client_bytes{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Total recv bytes(cluster)"
    },
    {
     "expr": "predixy_total_recv_client_bytes{namespace=\"$namespace\", service=\"$redis\", pod=~\"$proxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Send Bytes",
   "type": "graph",
   "description": "display only when proxy is enabled.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(predixy_total_send_client_bytes{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Total send bytes(cluster)"
    },
    {
     "expr": "predixy_total_send_client_bytes{namespace=\"$namespace\", service=\"$redis\", pod=~\"$proxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "display only when proxy is enabled.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(predixy_cluster_accept{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Total connections (cluster)"
    },
    {
     "expr": "predixy_cluster_accept{namespace=\"$namespace\", service=\"$redis\", pod=~\"$proxy\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}