{
 "title": "Redis cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(redis_up, namespace)"
   },
   {
    "name": "redis",
    "label": "Redis cluster",
    "query": "query_result(kube_statefulset_labels{namespace=\"$namespace\", label_middleware=\"redis\"})"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(redis_instance_info{namespace=\"$namespace\", service=\"$redis\", redis_mode!=\"sentinel\"}, pod)"
   },
   {
    "name": "pvc",
    "label": "pvc",
    "query": "query_result(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\", pod=\"$pod\"})"
   },
   {
    "name": "db",
    "label": "db",
    "query": "label_values(redis_db_keys{namespace=\"$namespace\", service=\"$redis\"}, db)"
   },
   {
    "name": "pv",
    "label": "pv",
    "query": "query_result(kube_persistentvolumeclaim_info{namespace=\"$namespace\", persistentvolumeclaim=\"$pvc\"})"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Redis Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redis_instantaneous_ops_per_sec{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "The amount of memory that a Redis instance is request.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(redis_memory_used_rss_bytes{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Total memory usage"
    },
    {
     "expr": "redis_memory_used_rss_bytes{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",endpoint!=\"\",container!=\"\"}[5m]) ) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"}) by (pod)  * 100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory Usage(%)",
   "type": "graph",
   "description": "The percentage of requested memory resources that are actually being used by the Redis Pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",endpoint!=\"\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"memory\"}) by (pod) * 100",
     "legendFormat": "WorkingSet Mem(include Active Pages in the File System Cache)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\",pod=\"$pod\",endpoint!=\"\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"memory\"}) by (pod) * 100",
     "legendFormat": "Rss Mem"
    }
   ]
  },
  {
   "title": "Volume Usage(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "used_size_kb{pv=\"$pv\"}*100/total_size_kb{pv=\"$pv\"}",
     "legendFormat": "Volume Usage-Hitachi"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_instantaneous_ops_per_sec{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Total QPS(cluster)"
    },
    {
     "expr": "redis_instantaneous_ops_per_sec{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\"}",
     "legendFormat": "'{{pod}}"
    }
   ]
  },
  {
   "title": "Number of blocked client connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_blocked_clients{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Number of blocked client connections(cluster)"
    },
    {
     "expr": "redis_expired_keys_total{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of client connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Number of client connections(Cluster)"
    },
    {
     "expr": "redis_connected_clients{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of rejected connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_rejected_connections_total{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Number of rejected connections(cluster)"
    },
    {
     "expr": "redis_rejected_connections_total{namespace=\"$namespace\", service=\"$redis\", pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total{namespace=\"$namespace\", service=\"$redis\"}[5m]))",
     "legendFormat": "Commands Executed / sec(cluster)"
    },
    {
     "expr": "rate(redis_commands_processed_total{namespace=\"$namespace\", service=\"$redis\", pod=\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Keys(cluster)"
    },
    {
     "expr": "redis_db_keys{namespace=\"$namespace\", service=\"$redis\", pod=\"$pod\", db=\"$db\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_expired_keys_total{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Expired Keys(cluster)"
    },
    {
     "expr": "redis_expired_keys_total{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys_expiring{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Expiring Keys(cluster)"
    },
    {
     "expr": "redis_db_keys_expiring{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\", db=\"$db\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Evicted Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_evicted_keys_total{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Evicted Keys(cluster)"
    },
    {
     "expr": "redis_expired_keys_total{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hits / Total per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_keyspace_hits_total{namespace=\"$namespace\", service=\"$redis\"}) / (sum(redis_keyspace_hits_total{namespace=\"$namespace\", service=\"$redis\"}) + sum(redis_keyspace_misses_total{namespace=\"$namespace\", service=\"$redis\"}))",
     "legendFormat": "Hits/Total per Sec(cluster)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Network(Output)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "redis_instantaneous_output_kbps{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-sent"
    }
   ]
  },
  {
   "title": "Network(Input)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "redis_instantaneous_input_kbps{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-received"
    }
   ]
  },
  { "title": "Big key", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "top n bigkey",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "topk(1000, sort(redis_big_key_top{namespace=\"$namespace\", service=\"$redis\", db=~\"$db\"}))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "big key count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_big_key_count{namespace=\"$namespace\", service=\"$redis\"})",
     "legendFormat": "Big Keys(cluster)"
    },
    {
     "expr": "redis_big_key_count{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\", db=~\"$db\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "big key avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(redis_big_key_avg{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\", db=~\"$db\"})",
     "legendFormat": "Bigkey-avg(cluster)"
    },
    {
     "expr": "redis_big_key_avg{namespace=\"$namespace\", service=\"$redis\", pod=~\"$pod\", db=~\"$db\"}",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  }
 ]
}