apiVersion: v1
stringData:
  endpoint: {{ .Release.Name }}.{{ .Release.Namespace }}.svc
  port: "{{ default .Values.redis.port .Values.redisServicePort }}"
  {{- if .Values.encodePassword }}
  password: "{{ (b64dec .Values.encodePassword) | default .Values.redisPassword }}"
  {{- else }}
  password: "{{ .Values.redisPassword }}"
  {{- end }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-credential
  namespace: {{ .Release.Namespace }}
type: Opaque
