{{- if  .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
{{- if .Values.predixy.enableProxy }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ include "redis.fullname" . }}
  name: {{ include "redis.fullname" . }}-proxy
spec:
  endpoints:
    - interval: 30s
      port: proxy-exporter
      relabelings:
      - replacement: redis
        targetLabel: middleware
      - sourceLabels: [service]
        replacement: {{ include "redis.fullname" . }}
        targetLabel: service
  selector:
    matchLabels:
      app: {{ include "redis.fullname" . }}
      component: {{ include "redis.fullname" . }}-predixy
{{- end }}
{{- end }}
