{{/*
Get DataPath Annotationn value
*/}}
{{- $redisFullName := include "redis.fullname" . -}}
{{- $dataPath := printf "/data/redis/cluster.local/%s/%s/{POD_NAME}/data" .Release.Namespace $redisFullName -}}
{{- $logPath := printf "/data/redis/cluster.local/%s/%s/**/log/*.log" .Release.Namespace $redisFullName -}}
{{- $customVolumeDataName := "redis-data" -}}

{{- if .Values.customVolumes }}
{{/*set logPathIndex*/}}
{{$logPathIndex := include "helm.function.ifListMapHasValue" (list .Values.customVolumes "name" "redis-logs" "redis-data") }}

{{- range $key, $value := .Values.customVolumes }}
{{/*set dataPath*/}}
{{- if eq $value.name $customVolumeDataName }}
  {{- $dataPath = $value.mountPath }}
{{- end }}
{{/*set logPath*/}}
{{- if eq $value.name $logPathIndex }}
  {{- $logPath = $value.mountPath }}
  {{- $logPath = printf "%s/*.log" $logPath}}
{{- end }}
{{- end }}
{{- end }}


apiVersion: redis.middleware.hc.cn/v1alpha1
kind: RedisCluster
metadata:
  annotations:
    datapath: {{$dataPath}}
  labels:
    nephele/user: admin
  name: {{ include "redis.fullname" . }}
spec:
  {{- if .Values.encodePassword }}
  secretName: {{ .Release.Name }}-credential
  {{- end }}
  {{- with .Values.env }}
  env:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.hostVolumes }}
  hostVolumes:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  statefulset:
    spec:
      template:
        metadata:
          {{- with .Values.annotations }}
          annotations:
          {{- toYaml . | nindent 13 }}
          {{- end }}
          {{- with .Values.labels }}
          labels:
          {{- toYaml . | nindent 13 }}
          {{- end }}
        spec:
        {{- with .Values.statefulSetConfiguration }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
        {{- toYaml . | nindent 13 }}
        {{- end }}
{{- if eq .Values.type "sentinel" }}
  deployment:
    spec:
      template:
        metadata:
          {{- with .Values.annotations }}
          annotations:
          {{- toYaml . | nindent 13 }}
          {{- end }}
          {{- with .Values.labels }}
          labels:
          {{- toYaml . | nindent 13 }}
          {{- end }}
        spec:
        {{- with .Values.sentinelConfiguration }}
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
        {{- toYaml . | nindent 12 }}
        {{- end }}
  type: sentinel
  sentinel:
    affinity:
      {{- if eq (semverCompare ">= 1.19-0" .Capabilities.KubeVersion.Version) false }}
      {{- if eq .Values.podAntiAffinity "hard"}}
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - {{ include "redis.fullname" . }}
          topologyKey: {{ .Values.podAntiAffinityTopologKey }}
      {{- else if eq .Values.podAntiAffinity "soft"}}
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: {{ .Values.podAntiAffinityTopologKey }}
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "redis.fullname" . }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      nodeAffinity:
      {{- toYaml . | nindent 8}}
      {{- end }}
    {{- if eq (semverCompare ">= 1.19-0" .Capabilities.KubeVersion.Version) true }}
    topologySpreadConstraints:
    {{- if ne .Values.podAntiAffinityTopologKey "kubernetes.io/hostname"}}
    - maxSkew: 1
      topologyKey: {{ .Values.podAntiAffinityTopologKey | default "" }}
      {{- include "middlware.sentinel.whenUnsatisfiable" . | nindent 6}}
      labelSelector:
        matchLabels:
          app: {{ include "redis.fullname" . }}
          component: {{ include "redis.fullname" . }}-sentinel
    {{- end }}
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      {{- include "middlware.sentinel.whenUnsatisfiable" . | nindent 6}}
      labelSelector:
        matchLabels:
          app: {{ include "redis.fullname" . }}
          component: {{ include "redis.fullname" . }}-sentinel
    {{- end }}
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: REDIS_INSTANCE_PORT
      value: "{{(int .Values.sentinel.port)}}"
    - name: TYPE
      value: "sentinel"
    - name: PODIP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - {{ printf "redis-cli -h $POD_IP -p %d ping" (int .Values.sentinel.port) }}
      timeoutSeconds: 5
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - {{ printf "redis-cli -h $POD_IP -p %d ping" (int .Values.sentinel.port) }}
      timeoutSeconds: 5
    {{- toYaml .Values.sentinel | nindent 4 }}
    {{- if .Values.sentinel.securityContext }}
    securityContext:
      runAsUser: {{ .Values.sentinel.securityContext.runAsUser | default 0 }}
      runAsGroup: {{ .Values.sentinel.securityContext.runAsGroup | default 0 }}
      fsGroup: 0
    {{- end }}
{{- else if eq .Values.type "cluster" }}
  type: cluster
{{- else if eq .Values.type "replication" }}
  type: replication
{{- end }}
{{- if eq .Values.type "clusterMultiSts" }}
  type: clusterMultiSts
{{- end }}
{{- template "middlware.proxy" . }}
  pod:
  - affinity:
      {{- if eq (semverCompare ">= 1.19-0" .Capabilities.KubeVersion.Version) false }}
      {{- if eq .Values.podAntiAffinity "hard"}}
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - {{ include "redis.fullname" . }}
          topologyKey: {{ .Values.podAntiAffinityTopologKey }}
      {{- else if eq .Values.podAntiAffinity "soft"}}
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: {{ .Values.podAntiAffinityTopologKey }}
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "redis.fullname" . }}
      {{- end}}
      {{- end}}
      {{- if eq (empty .Values.redis.nodeAffinity) true }}
      {{- with .Values.nodeAffinity }}
      nodeAffinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      nodeAffinity:
      {{- toYaml .Values.redis.nodeAffinity | nindent 8 }}
      {{- end }}
    {{- if eq (semverCompare ">= 1.19-0" .Capabilities.KubeVersion.Version) true }}
    topologySpreadConstraints:
    {{- if ne .Values.podAntiAffinityTopologKey "kubernetes.io/hostname"}}
    - maxSkew: 1
      {{- if eq (empty .Values.redis.topologyKey) true }}
      topologyKey: {{ .Values.podAntiAffinityTopologKey | default "" }}
      {{- else }}
      topologyKey: {{ .Values.redis.topologyKey | default "" }}
      {{- end }}
      {{- include "middlware.whenUnsatisfiable" . | indent 6}}
      labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - {{ include "redis.fullname" . }}
        - key: component
          operator: NotIn
          values:
          - {{ include "redis.fullname" . }}-sentinel
          - {{ include "redis.fullname" . }}-predixy
    {{- end }}
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      {{- include "middlware.whenUnsatisfiable" . | indent 6}}
      labelSelector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - {{ include "redis.fullname" . }}
          - key: component
            operator: NotIn
            values:
              - {{ include "redis.fullname" . }}-sentinel
              - {{ include "redis.fullname" . }}-predixy
    {{- end}}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end}}
    annotations:
      fixed-node-middleware-pod: "true"
      fixed.ipam.{{.Values.company | default "harmonycloud"}}.cn: "true"
    configmap: {{ include "redis.fullname" . }}-config
    env:
    - name: MAXMEMORY
      value: {{ .Values.redisMaxMemory }}
    - name: SYS_CODE
      value: {{ include "redis.fullname" . }}
  {{- if ((((.Values.logging).collection).stdout).enabled)}}
    - name: aliyun_logs_middlewarestdout
      value: stdout
    - name: aliyun_logs_middlewarestdout_tags
      value: middleware_name={{ include "redis.fullname" . }}
  {{- end}}
  {{- if ((((.Values.logging).collection).filelog).enabled)}}
    - name: aliyun_logs_middlewarelogstash
      value: {{$logPath}}
    - name: aliyun_logs_middlewarelogstash_tags
      value: middleware_name={{ include "redis.fullname" . }}
  {{- end}}
    labels:
      {{.Values.company | default "harmonycloud"}}.cn/statefulset: {{ include "redis.fullname" . }}
      middleware: redis
      nephele/user: admin
  {{- if eq .Values.version "5.0.8" }}
    middlewareImage: redis-cli-v5-port:{{ .Values.image.redisImageTag }}
  {{- end}}
  {{- if eq .Values.version "6.2.6"}}
    middlewareImage: redis-cli-v6-port:{{ .Values.image.redisImageTag_6 }}
  {{- end}}
  {{- if eq .Values.version "6.2.11"}}
    middlewareImage: redis-cli-v6-port:{{ .Values.image.redisImageTag_6_11 }}
  {{- end}}
  {{- if eq .Values.version "6.2.14"}}
    middlewareImage: redis-cli-v6-port:{{ .Values.image.redisImageTag_6_2_14 }}
  {{- end}}
  {{- if eq .Values.version "6.2.16"}}
    middlewareImage: redis-cli-v6-port:{{ .Values.image.redisImageTag_6_2_16 }}
  {{- end}}
  {{- if eq .Values.version "6.2.18"}}
    middlewareImage: redis-cli-v6-port:{{ .Values.image.redisImageTag_6_2_18 }}
  {{- end}}
  {{- if eq .Values.version "7.0.12"}}
    middlewareImage: redis-cli-v7-port:{{ .Values.image.redisImageTag_7_0_12 }}
  {{- end}}
  {{- if eq .Values.version "7.0.15"}}
    middlewareImage: redis-cli-v7-port:{{ .Values.image.redisImageTag_7_0_15 }}
  {{- end}}
  {{- if eq .Values.version "7.2.4"}}
    middlewareImage: redis-cli-v7-port:{{ .Values.image.redisImageTag_7_2_4 }}
  {{- end}}
  {{- if eq .Values.version "7.2.8"}}
    middlewareImage: redis-cli-v7-port:{{ .Values.image.redisImageTag_7_2_8 }}
  {{- end}}
    initImage: redis-init:{{ .Values.image.initImageTag }}
    monitorImage: redis-exporter:{{ .Values.image.exporterImageTag }}
    logrotateImage: logrotate:{{ .Values.image.logrotateImageTag}}
    requirepass: {{ .Values.redisPassword | quote}}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    hostNetwork: {{ default false .Values.redis.hostNetwork }}
    resources:
      {{- toYaml .Values.redis.resources | nindent 6 }}
    updateStrategy: {}
    {{- if .Values.redis.securityContext }}
    securityContext:
      runAsUser: {{ .Values.redis.securityContext.runAsUser }}
      fsGroup: 0
      runAsGroup: {{ .Values.redis.securityContext.runAsGroup }}
    {{- end }}
    {{- if .Values.redis.command }}
    command: {{ .Values.redis.command }}
    {{- end }}
    {{- if .Values.redis.externalAccess }}
    externalAccess:
      {{- toYaml .Values.redis.externalAccess | nindent 6 }}
    {{- end }}
  exporter:
    {{- toYaml .Values.exporter | nindent 4 }}
    port: {{ .Values.exporter.port }}
    {{- if .Values.exporter.rdbScan }}
    rdbScan:
      enable: {{ .Values.exporter.rdbScan.enable }}
      interval: {{ .Values.exporter.rdbScan.interval }}
      filePath: {{$dataPath}}
      bigKeyLen: {{ .Values.exporter.rdbScan.bigKeyLen }}
      bigKeyThreshold: {{ .Values.exporter.rdbScan.bigKeyThreshold }}
    {{- end}}
  podManagementPolicy: Parallel
  replicas: {{ .Values.redis.replicas }}
  servicePort: {{ default .Values.redis.port .Values.redisServicePort }}
  repository: {{ .Values.image.repository }}/
  updateStrategy:
  {{- toYaml .Values.updateStrategy | nindent 4 }}
  version: "{{ .Values.version}}"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.storageClassName }}
      storageClassName: {{ .Values.storageClassName }}
      {{- end}}
      resources:
        requests:
          storage: {{ .Values.storageSize }}
  {{- if .Values.customVolumes }}
  customVolumes:
  {{- toYaml .Values.customVolumes | nindent 4 }}
  {{- end }}
{{- if eq .Values.type "clusterMultiSts" }}
  clusterMultiSts:
    {{- toYaml .Values.clusterMultiSts | nindent 4 }}
{{- end}}
